### ISSUE TITLE
Tutorial experimentos ML

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#10]
Fazer um tutorial de como está sendo feito os experimentos ML com os dados do Salic (para facilitar/incentivar a contribuição).
Sugestão: fazer um notebook tutorial (guia)

**Comment by Duerno** [comment]
Oi Carla, esta issue está relacionada com as issues #29 e #30, então vou fechar esta e você acompanha os resultados pela #29.
