### ISSUE TITLE
Resolver problema de paginação do front end

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#100]
A paginação está demorando muito tempo.

- [ ] Colocar um loading enquanto os dados não estão prontos

**Comment by LucianoPC** [comment]
Tem um timer para aguardar os dados serem paginados.

Vai ser refatorado para fazer a paginação no backend

**Comment by victorcmoura** [comment]
O loading na versão monolítica já existe mas ainda existe possibilidade de melhoria na versão API + Frontend VueJS. Issue transferida para em https://github.com/lappis-unb/salic-ml-web/issues/2
