### ISSUE TITLE
Visualização dos resultados da homologação

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#102]
A homologação com os técnicos do MinC vai resultar em dados que informam se os indicadores são úteis, então é necessário visualizar esses dados

**Comment by LucianoPC** [comment]
Fazer algo para gerar os csvs e disponibilizar eles no google drive
Em tempo real??

**Comment by rodmaia2099** [comment]
Não precisa ser necessariamente em tempo real, mas que pelo menos a gente consiga disparar o processo que gera esse CSV quando quisermos olhar para os resultados.

**Comment by victorcmoura** [comment]
Issue transferida para https://github.com/lappis-unb/salic-ml-web/issues/22
