### ISSUE TITLE
Reformular a arquitetura do salic-ml-web

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#103]
Tem que definir quais são e como vão funcionar os microsserviços

**Comment by victorcmoura** [comment]
Após brainstorm com o time, :

![image](https://user-images.githubusercontent.com/26290053/44676172-de400d00-aa08-11e8-8545-e4e95356a2ce.png)

**Comment by rodmaia2099** [comment]
A reformulação está concluída ou não? 
Se sim: quais issues derivaram disso e por que esta issue aqui não foi fechada?
Se não: o que falta? Por que não foi documentado aqui?

**Comment by victorcmoura** [comment]
A reformulação foi feita de maneira empírica. Deve existir estudo sobre o assunto para termos embasamento de que realmente estamos implementando algo inteligente. Para isso, foi criada uma issue em https://github.com/lappis-unb/salic-ml-web/issues/16 para atingirmos o nosso objetivo. Estou transferindo a discussão para lá.
