### ISSUE TITLE
Atualizar os CSVs no servidor FTP

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#105]
Dado que o banco de dados de homologação foi atualizado com dados válidos de produção, é preciso atualizar os datasets do servidor FTP.

**Comment by marlonbymendes** [comment]
Verificar a possiblidade de automatizar este processo (baixar .csv dada uma query SQL, subir um .csv para o ftp).

**Comment by LucianoPC** [comment]
Foi feito um script para baixar os dados do banco utilizando a query do ".sql"

Já está atualizando o FTP

Falta terminar de colocar alguns arquivos csv's no FTP e fazer o Pull Request
