### ISSUE TITLE
Adicionar medida de quão crítico é um outlier às features implementadas

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#106]
Atualmente, as features de complexidade financeira contam apenas com um atributo binário, alertando se o projeto é um outlier ou não, em relação a uma métrica específica. Queremos granularizar essa informação: medir quão outlier é um projeto com relação a uma feature.
Adicionar granularidade a todas as features implementadas e documentar o intervalo possível de valores e seus significados.

**Comment by LucianoPC** [comment]
É uma escala de 0 a 1 que indica o quão outlier é.

Falta as que não tem medida de outlier, e a do Duerno.
