### ISSUE TITLE
Formalizar resultados SALIC ML

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#107]
Documentar o Produto/Projeto SALIC ML de forma didática (para dar sustentabilidade ao projeto e escalabilidade)

- [ ] Criar o gitpage do salic-ml

- [ ] Documentar a visão de produto (além do próprio Minc) - uso de data Science para apoiar a prestação de contas de políticas públicas de fomento

- [x] Roadmap do projeto (2 anos)

- [ ] Resultados preliminares - Estudo de caso Minc - quais foram os principais resultados encontrados ao explorar os dados do salic (resultados 1/2018)

- [x] Metodologia de trabalho - times, papeis, fluxo de trabalho

- [ ] Notebooks - como é usado no projeto e template

- [ ] Frente Pesquisa - como é tratado o pipeline (dado, feature extraction, algoritmos, verificação, validação)

- [ ] Frente Arquitetura Salic-ML - documentação

- [ ] Homologação - documentação do processo

Esse trabalho é super importante tanto para a entrada de novos integrantes no projeto, para registrar os avanços, e também pode ser insumo para futuras publicações dos resultados desse trabalho. 

Exemplo de como essa documentação já é feita em outros projetos de pesquisa:
https://github.com/facebookresearch/DensePose

**Comment by rodmaia2099** [comment]
Me parece que criamos essa issue depois da primeira apresentação de resultados do SALIC-ML. Quais foram as tarefas acima que conseguimos avançar?

**Comment by danielgs83** [comment]
Mudei bastante nosso [roadmap](https://github.com/lappis-unb/salic-ml/wiki/Roadmap-do-Salic-ML) tentando readequá-lo à realidade técnica nossa e à expectativa de entregas para homologação. Preciso que revisem as minhas sugestões, @RochaCarla @Duerno @marlonbymendes @rodmaia2099

**Comment by victorcmoura** [comment]
Ao que a descrição indica, estes tópicos estão sendo abordados pela issue #282.
