### ISSUE TITLE
Gravar o estado do Salic-ML em homologação

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#108]
Fazer uma tag
Fazer uma release
Salvar a imagem no registry do gitlab com a tag

**Comment by rodmaia2099** [comment]
@LucianoPC e @victorcmoura lendo essa issue não consigo estimar se é um trabalho trivial de 15 minutos ou se é algo pesado que leva dias. Ignorância minha.

Se for um esforço de mais de 30min, sugiro quebrar em issues menores. Façam o exercício de pensar passo-a-passo o que precisa ser feito e documentar na issue para evitarmos surpresas de última hora.

**Comment by victorcmoura** [comment]
É uma issue de menos de 30min. Estou transferindo-a para o repositório [salic-ml-web](https://github.com/lappis-unb/salic-ml-web/issues)

**Comment by victorcmoura** [comment]
Issue disponível em outro repositório: https://github.com/lappis-unb/salic-ml-web/issues/18
