### ISSUE TITLE
Aumentar a capacidade da VM de Homologação no MinC

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#112]
A VM está com pouco espaço e aí o serviço fica caindo.

Conversando com o Matheus Faria levantamos a ideia de os outros projetos do LAPPIS com o MinC usarem a mesma VM, perguntei para o Marcus (o responsável no MinC) e ele permitiu.

Para que tenha mais projetos usando essa mesma VM é necessário aumentar mais a capacidade dela também, logo vou solicitar a seguinte configuração para a VM:

/          - 10GB
/var     - 30GB
/home - 20GB
memóra: 16GB

**Comment by LucianoPC** [comment]
O Marcus me informou que já abriu o pedido para a infra do MinC aumentar a capacidade

**Comment by rodmaia2099** [comment]
Qual a previsão de isso ser feito do lado do MinC?

**Comment by victorcmoura** [comment]
Issue transferida para https://github.com/lappis-unb/salic-ml-web/issues/21
