### ISSUE TITLE
Atualizar datasets para inclusão de colunas necessárias para geração de link para o SALIC

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#123]
- [ ] Atualizar todos os `.sql` envolvidos
- [ ] Atualizar o ftp com os novos datasets (`.csv`)

A issue #117 levantou a necessidade das seguintes dos seguintes dados para cada item:

- idPronac (id numérico)
- UfItem (string, exemplo 'SP')
- idProduto (id numérico)
- idMunicipioIBGE (id numérico)
- idPlanilhaItem (id numérico)
- cdEtapa (id numérico)

Vide este [comentário](https://github.com/lappis-unb/salic-ml/issues/117#issuecomment-418941743).

**Comment by victorcmoura** [comment]
Dadas as reuniões realizadas desde a abertura desta issue, verificou-se a inviabilidade de se montar os links da maneira que gostaríamos. Além disso, a reestruturação da arquitetura facilitou a obtenção destes dados diretamente do banco de dados. Havendo a necessidade da existência destes links no frontend, uma nova issue deverá ser aberta.
