### ISSUE TITLE
Indicador de complexidade do proponente

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#125]
* [ ] Implementar métricas que fornecem insumos para mensurar a complexidade de um proponente
    1. Histórico de problemas/diligências
* [ ] Utilizar métricas para implementar score de complexidade do proponente
* [ ] Documentação das funcionalidades implementadas, entradas/saídas, jupyter notebook organizado

**Comment by RochaCarla** [comment]
vai ser aberto uma issue melhor detalhada
