### ISSUE TITLE
Indicador de complexidade do fornecedor

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#126]
* [ ] Implementar métricas que fornecem insumos para mensurar a complexidade de um fornecedor
    1. Histórico de problemas/~~diligências de projeto~~ com aquele fornecedor 
    1. Análise de "fraude" criando uma rede/grafo de fornecedores
    1. Porcentagem do capital do(s) projeto(s) reservados para o fornecedor
    1. Identificação de fornecedores coligados/familiares/societários
    1. Identificação de reciprocidade entre proponentes e fornecedores (pessoas que frequentemente alternam os papeis de proponente e fornecedor em projetos diferentes mas sempre trabalham juntas. Por outro lado, proponentes e fornecedores que sempre trabalham juntos sem alternância de papeis não é um problema)
* [ ] Utilizar métricas para implementar score de complexidade do fornecedor
* [ ] Documentação das funcionalidades implementadas, entradas/saídas, jupyter notebook organizado

**Comment by rodmaia2099** [comment]
Diligências estão descartadas como métricas de complexidade depois de conversa com a equipe SEFIC 26/10/2018, pois diligências são uma feature muito recente no SALIC e não há histórico

**Comment by victorcmoura** [comment]
Análise dos CPFs/CNPJs envolvidos no processo de incentivo cultural está sendo realizada em um repositório privado.

**Comment by rodmaia2099** [comment]
A análise exclusiva da complexidade dos fornecedores está descartada porque esses atores participam passivamente do incentivo cultural. Não há formas de alterar a participação de pessoas ou empresas como fornecedores. A menos em caso de fraude, mas esses casos serão tratados pelo escore de proponente.
