### ISSUE TITLE
Indicador de complexidade de serviços

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#127]
* [ ] Implementar métricas que fornecem insumos para mensurar a complexidade de um serviços
    1. Variação de valores de serviços
* [ ] Utilizar métricas para implementar score de complexidade do serviços
* [ ] Documentação das funcionalidades implementadas, entradas/saídas, jupyter notebook organizado

**Comment by RochaCarla** [comment]
fora de escopo do projeto
