### ISSUE TITLE
Indicador de complexidade temporal

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#128]
* [ ] Implementar métricas que fornecem insumos para mensurar a complexidade temporal
    1. Análise do histórico de adições/remoções de itens da planilha orçamentária na execução do projeto
    1. Análise do histórico de alterações de preços de itens
    1. Análise do histórico de anexos de comprovantes à planilha orçamentária
* [ ] Utilizar métricas para implementar score de complexidade do proponente
* [ ] Documentação das funcionalidades implementadas, entradas/saídas, jupyter notebook organizado

**Comment by victorcmoura** [comment]
Dadas as discussões e reuniões realizadas desde a abertura desta issue, verificou-se que esta métrica não agrega valor para o projeto neste momento.
