### ISSUE TITLE
Identificar comprovantes suspeitos

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#129]
Utilizar dados de indicadores de complexidade e técnicas de amostragem para identificar os itens mais críticos de um projeto cultural.
Deve ser possível passar um índice de confiança como argumento para que a função retorne todos os itens cujo comprovante deve ser verificado para que o projeto seja marcado como analisado e aceito com a taxa de confiança dada.

**Comment by RochaCarla** [comment]
nao faz parte do roadmap
