### ISSUE TITLE
Pesquisar a arquitetura do salic-ML

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#131]
Critérios de aceitação:

- [ ] Desacoplar extração de features da fonte dos dados
- [ ] Desacoplar algorítmos de ML da extração de features
- [ ] Prever treinamento periódicos
- [ ] Escalabilidade de features: adição ou remoção de features
- [ ] Eficiência no processo de extração de features

Os seguintes problemas atuais devem ser levados em consideração para a definição da nova arquitetura:
1. Etapa de geração de features e de geração das métricas está acoplada: dificulta o desenvolvimento dessas etapas de forma separada e métricas distintas que utilizam as mesmas features precisam recalculá-las gerando processamento desnecessário
1. Os testes são muito demorados: sempre que é preciso testar alguma parte da aplicação, todos os testes são executados, cada conjunto de testes precisa reexecutar todo o pré-processamento e geração de todas as métricas

Artefato: proposta arquitetura (.md)

**Comment by AlexandreTK** [comment]
Achei interessante a arquitetura proposta no seguinte site: [](http://www.wideskills.com/data-mining-tutorial/data-mining-architecture)

Imagem:
<img width="711" alt="screen shot 2018-09-10 at 11 40 33 am" src="https://user-images.githubusercontent.com/10123141/45304386-5ff66700-b4ee-11e8-9887-38379b96abb7.png">

**Comment by AlexandreTK** [comment]
Algumas adaptações poderiam ser feitas como, por exemplo:
- Unir "Pattern Evaluation" e "Data mining Engine".
- Substituir "Graphical User Interface" por uma "API". A "API" teria acesso ao "Knoledge Base" e "Database or Data Warehouse Server".

**Comment by marlonbymendes** [comment]
Esta [página](https://github.com/lappis-unb/salic-ml/wiki/Desenvolvimento-Arquitetura-ML) contém os resultados de algumas discussões sobre a arquitetura do ML. Em paralelo, está sendo desenvolvido na branch [architecture_v0](https://github.com/lappis-unb/salic-ml/tree/architecture_v0) uma versão da proposta de arquitetura.

**Comment by RochaCarla** [comment]
Abrir issues de implementacao para avaliar e viabilidade técnica da arquitetura.
@LucianoPC @marlonbymendes colocar aqui a issue de implementação

**Comment by RochaCarla** [comment]
https://mlflow.org
