### ISSUE TITLE
Investigar alta ocorrência de métricas indisponíveis

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/salic-ml#135]
Atualmente na versão de homologação (https://salicml.lappis.rocks) existe um volume muito grande de projetos com dados indisponíveis.

Isso pode ocorrer:

* porque o BD de homologação do MinC tem muitos dados zerados/indisponíveis;
* porque estamos listando projetos que ainda não estão na fase de análise de resultados;
* por outros motivos desconhecidos.

Devemos investigar o problema e em seguida propor uma solução para a equipe decidir.

**Comment by marlonbymendes** [comment]
Possíveis razões para este comportamento:

1) Existem mais projetos que não completaram a fase de Análise de Resultados do que os que completaram, portanto é normal ter mais dados indisponíveis (no banco de dados) do que disponíveis no sentido de métricas como: total comprovado, número de comprovantes, fornecedores etc.

2) O módulo do ML não faz discriminação em termos da fase do projeto, ele apenas recebe um identificador do projeto (PRONAC), calcula as métricas quando possível e retorna o resultado. Portanto se nenhum filtro adicional (no backend, por ex.) tiver sido feito, os projetos serão exibidos no front-end independentemente em qual fase o projeto esteja (ex. Aprovação).

3) Dado disponível no banco de dados, mas indisponível no front-end. Este seria um bug de fato no sentido de que foi um erro a nível de código. Porém é necessário ter um exemplo de projeto ou PRONAC que demonstre esta inconsistência.

**Comment by rodmaia2099** [comment]
@marlonbymendes concordo com a análise. Essa questão das fases do projeto precisa ser esclarecida de uma vez por todas porque compromete a qualidade do nosso produto, estando relacionada a esse problema dos zeros ou não.
O @LucianoPC já fez um esforço de tentar achar a resposta. Acho que precisamos apelar para as instâncias superiores. Talvez a @RochaCarla possa verificar quem é a pessoa que vai responder isso pra gente. Talvez seja o próprio Rômulo.

**Comment by victorcmoura** [comment]
Dadas as explicações dadas na época, esta issue será fechada.
