### ISSUE TITLE
Encontrar contra exemplos que evidencie a limitação atual do ML

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#149]
A proposta inicial de complexidade foi baseada em uma abordagem ingênua a partir da hipótese que todos os dados  possuem distribuição Gaussiana. 

Precisamos evidenciar as limitações dessa abordagem. 

**Tarefas**
- [x] Encontrar projetos que tiveram muitas diligências (>= 2) e com pouca complexidade

**Critério de aceitação:**

- [x] Identificado um conjunto de projetos que possuem irregularidades/diligências e que o sistema não identificou (nível itens)

- [x] Resultados disponíveis em uma ou mais páginas `.md` na wiki

**Comment by victorcmoura** [comment]
Projetos que tiveram problemas que, inclusive, viraram notícia:

NOME DO PROJETO: Minha Cidade
PRONAC: 152405

NOME DO PROJETO: Caminhos Sinfônicos
PRONAC: 153640

Fonte: https://oglobo.globo.com/brasil/mpf-denuncia-32-pessoas-por-fraudes-na-lei-rouanet-para-pagar-festas-1-22035178

**Comment by marlonbymendes** [comment]
Faltando apenas a página na wiki.

**Comment by AlexandreTK** [comment]
Avaliação na Wiki:
- [https://github.com/lappis-unb/salic-ml/wiki/Avaliação-do-SALIC-ML](https://github.com/lappis-unb/salic-ml/wiki/Avaliação-do-SALIC-ML)

Exemplos de diligencias de projetos com notas boas(0%) e ruins (81%) pelo Salic-ml:
- Documento "Diligencias_Avaliacao_sistema.csv" no Google Drive do Salic-ml

**Comment by RochaCarla** [comment]
Excelente! A tabela tem o texto das diligências, e várias são referente à itens da planilha orçamentária. Vale a pena abrir uma issue similar a cada refinamento/ novas features

**Comment by RochaCarla** [comment]
Dúvida:
