### ISSUE TITLE
Categorizar projetos

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#15]
- Quais outros projetos são os mais similares a um determinado projeto?
- A qual categoria pertence um determinado projeto?

Sugestão: trabalhar inicialmente com uma base de dados reduzida, selecionando dois conjuntos de projetos de categorias bem distintas. Melhorar a detecção de similaridade de classificação de tais projetos com engenharia de características, e depois testar tal classificação para categorias mais semelhantes.

**Comment by LucianoPC** [comment]
Observar issue #17

**Comment by marlonbymendes** [comment]
Fechando a issue enquanto ela não estiver atrelada a uma entrega específica.
