### ISSUE TITLE
Preparar reunião estratégica 28/09

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#150]
Preparar para a reunião estratégica do dia 28/09, às 14h30, na SEFIC

**Tarefas**:

- [x]  Escrever Metas Estratégicas para a próxima etapa
- [x]  Escrever roadmap com as entrega para os próximos 3 meses
- [x] Implementar Roadmap para homologação/produção da frente ML
- [x] Implementar Roadmap para integração com o SaliC

**Critérios de aceitação:**

- [x] Link da apresentação (disponível no google drive)
- [x] Validação ok pela equipe

**Comment by RochaCarla** [comment]
https://docs.google.com/presentation/d/1RAOVYnnGDN_1LwTDDQIFrHOi7E1YuStJfVJVs_N9cVY/edit?usp=sharing

**Comment by marlonbymendes** [comment]
- Incluir Épica de arquitetura
- Detalhar Integração
- Validar as propostas

**Comment by ricardopoppi** [comment]
Fiz a inclusão do slide de integração com o status atual da discussão com o cgtec e o time da ufabc
