### ISSUE TITLE
Relatório de acompanhamento 04

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#151]
Relatório de acompanhamento das atividades da equipe (frente salicML) no período de julho 2018 à  setembro 2018

**Critérios de aceitação:**

- [x] Seções organizadas sobre os itens a ser abordado (SALIC pesquisa + SALIC arquitetura)

- [x] Anexos pertinentes das atividades

- [x] Documentos produzidos no período

**Comment by RochaCarla** [comment]
https://github.com/lappis-unb/EcossistemasSWLivre/tree/master/Relatorios/R3

**Comment by danielgs83** [comment]
Segue sugestão inicial para a frente de pesquisa: https://github.com/lappis-unb/salic-ml/wiki/Itens-para-o-relat%C3%B3rio-4---Frente-SALIC-ML-Pesquisa
