### ISSUE TITLE
Dados disponibilizados para cálculo das features

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#154]
Features tem que ser calculadas com projetos que estão ou já passaram pela a análise financeira.

- [ ] usar dados somente de projetos na fase de analise financeira ou posterior

- [ ] Para cada projeto, todas as metricas sao calculadas com a mesma base de dados (conjunto de projetos)

**Comment by victorcmoura** [comment]
Deprecated
