### ISSUE TITLE
Implementar métrica de números de itens na arquitetura proposta

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#155]
Apresentar a viabilidade técnica da arquitetura proposta

**Tarefas**:

- [x] Obter especificação do formato do JSON
- [x] Definir ferramenta de análise estática (PEP8, Flake8 por ex.) 
- [x] Implementar integração contínua no GitlabCI

**Critérios de aceitação:**

- [x] Implementação em um novo repositório

- [x] JSON fornecido no formato especificado pelo front-end (issue https://github.com/lappis-unb/salic-ml-web/issues/45)

- [x] Testes unitários com sucesso

- [x] Análise estática completa (sem warnings)

- [x] Integração contínua

- [x] Disponibilizar a métrica "rodando" no pipeline de integração contínua X

- [ ] IP públic no ambiente de dev , acessível pelo browser, que forneça a resposta (.json) para qualquer PRONAC dado

- [x] Docstring de todas as classes

**Comment by RochaCarla** [comment]
Abrir Outro repositório

**Comment by eduardonunes2525** [comment]
```json
{
    "name": "itens_orcamentarios",
    "name_title": "Itens orçamentários",
    "helper_text":
      "Compara a quantidade de itens deste projeto com a quantidade mais comum de itens em projetos do mesmo segmento",
    "value": "string",
    "value_text": "string",
    "value_is_valid": "booleano",
    "outlier_check": "string => podendo ser: Metric-bad || Metric-good",
    "type": "bar",
    "bar":  {
    		"interval_start": "Inteiro",
    		"interval_end": "Inteiro",
    		"interval": "Inteiro",
    		"max_value": "Inteiro"
  	},
    
    "reason": "string"
  }
```

**Comment by marlonbymendes** [comment]
Exemplo de saída da api:

```
{
  "bar": {
    "interval": 57, 
    "interval_end": 129, 
    "interval_start": 0, 
    "max_value": 258
  }, 
  "helper_text": "Compara a quantidade de itens deste projeto com a quantidade mais comum de itens em projetos do mesmo segmento", 
  "name": "itens_orcamentarios", 
  "name_title": "Itens orçamentários", 
  "outlier_check": "Metric-bad", 
  "reason": "", 
  "type": "bar", 
  "value": 57, 
  "value_is_valid": "True"
}
```

**Comment by marlonbymendes** [comment]
O endereço https://lappislearning.dev.lappis.rocks/metric/number_of_itens/164274 não está disponibilizando o resultado da métrica no formato esperado.

**Comment by LucianoPC** [comment]
O JSON definido para ser usado no salic-ml vai ser redefinido, vou conversar com o @eduardonunes2525

**Comment by RochaCarla** [comment]
Issue fechada pois a tarefa relacionada a disponibilizar foi realocada na issue #230
