### ISSUE TITLE
Evoluir notebooks pesquisa ML para comparar Gaussiana com LOF

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#156]
**Tarefas:**

- [x] Realizar pesquisa sobre LOF

- Adicionar seção de LOF para todas as métricas calculadas (com ou sem notebook):
    - [ ] Approved Funds
    - [ ] Common Items Ratio
    - [ ] Items Prices
    - [ ] New Providers
    - [ ] Number Of Items
    - [ ] Proponent Projects
    - [ ] Raised Funds
    - [ ] Total Receipts
    - [ ] Verified Funds

- Adicionar uma seção avaliando os resultados:
    - [ ] Approved Funds
    - [ ] Common Items Ratio
    - [ ] Items Prices
    - [ ] New Providers
    - [ ] Number Of Items
    - [ ] Proponent Projects
    - [ ] Raised Funds
    - [ ] Total Receipts
    - [ ] Verified Funds

**Critérios de aceitação:**

- [ ] Notebook apresentando os resultados da validação cruzada com o método da gaussina vs método do LOF
- [ ] Conclusão sobre qual método é o mais adequado para o contexto

**Comment by RochaCarla** [comment]
Issue estava grande (problema de estimativa)

**Comment by marlonbymendes** [comment]
Quebrar esta issue em outras issues menores, detalhar em cada issue:

- Tarefas
- Critérios de aceitação

**Comment by victorcmoura** [comment]
Issue quebrada em outras 9:

- Approved Funds: https://github.com/lappis-unb/salic-ml/issues/169
- Common Items Ratio: https://github.com/lappis-unb/salic-ml/issues/172
- Iems Prices: https://github.com/lappis-unb/salic-ml/issues/174
- New Providers: https://github.com/lappis-unb/salic-ml/issues/176
- Number Of Items: https://github.com/lappis-unb/salic-ml/issues/171
- Proponent Projects: https://github.com/lappis-unb/salic-ml/issues/173
- Raised Funds: https://github.com/lappis-unb/salic-ml/issues/175
- Total Receipts: https://github.com/lappis-unb/salic-ml/issues/170
- Verified Funds: https://github.com/lappis-unb/salic-ml/issues/177
