### ISSUE TITLE
Metodologia proposta

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#157]
Padronização de práticas já realizadas no reposótio. 

**Tarefas:**

- [ ] Verificar viabilidade do gitpage, subir o gitpage caso seja viável
- [x] Pesquisar padrões de template ML

**Critérios de aceitação:**

- [ ] `How to contribute.md` atualizado na `master`

- [ ] Template de pull request na `master`

- [x] Template notebook (@LucianoPC subir) na `master`

**Comment by Duerno** [comment]
Template adicionado no PR #198

**Comment by victorcmoura** [comment]
Deprecated
