### ISSUE TITLE
Plano de comunicação

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#158]
Realizar o Plano de Comunicação

**Tarefas:**

- [ ] Identificar stakeholders

- [ ] Criar seção de "Quando Comunicar"

- [x] Criar seção  "O que Comunicar"

- [x] Criar seção "Canal de Comunicação"

**Critérios de aceitação:**

- [ ] O documento deve conter informações suficientes para que qualquer pessoa consiga executar o Plano
- [x] Disponível na wiki deste repositório

**Comment by victorcmoura** [comment]
Foi criado um template de Change Log. Disponível em: https://github.com/lappis-unb/salic-ml/wiki/Template-de-Change-Log

**Comment by RochaCarla** [comment]
O que significa a segunda parte do texto (são os erros mapeados ou futuras evoluções)?

**Comment by victorcmoura** [comment]
@RochaCarla Imagino que pode servir tanto para erros mapeados (indicando que estamos trabalhando em correções), quanto para futuras evoluções (indicando que, além de corrigir eventuais inconsistências, estamos trabalhando em novas features)

**Comment by victorcmoura** [comment]
Deprecated
