### ISSUE TITLE
Implementar barras em todas as métricas

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#160]
Deve existir uma barra indicando a colocação do projeto em relação aos outros do mesmo segmento

Migrado de: https://github.com/lappis-unb/salic-ml-web/issues/46

**Comment by eduardonunes2525** [comment]
Foi finalizada! Porém por não haver mais a necessidade de utilização da mesma por ter sido descontinuado a versão do monolítico a issue está sendo fechada.
