### ISSUE TITLE
Remover filtro de situação na lista de projetos

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#161]
Atualmente, há os seguintes filtros na lista de projetos:

- Filtro de situação
- Filtro de quantidade mínima de comprovantes (pelo menos um comprovante)

Deve-se remover o filtro de situação para permitir a busca por projetos já avaliados.

Migrado de: https://github.com/lappis-unb/salic-ml-web/issues/44

**Comment by victorcmoura** [comment]
Há a necessidade de se rever se o filtro é realmente desnecessário. Sabe-se que, atualmente, o filtro que indica a quantidade mínima de comprovantes não está sendo utilizado.

**Comment by rodmaia2099** [comment]
@victorcmoura É um filtro que as pessoas podem ativar ou desativar? Ou estamos filtrando direto na consulta e trazendo apenas projetos com prestação de contas abertas?

**Comment by rodmaia2099** [comment]
Segundo o @victorcmoura o filtro é aplicado no backend. A revisão desse filtro depende da equipe SEFIC para identificar as situações de projeto corretas. Mapeado em #240 .
