### ISSUE TITLE
Formato JSON Para View

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#162]
A presente issue está vinculado à: lappis-unb/salic-ml#155

Criterio de aceitação

- [x] documentar quais são os formatos JSON para consumo do fronted

- [x] Um exemplo de cada formato

Migrado de: https://github.com/lappis-unb/salic-ml-web/issues/45

**Comment by eduardonunes2525** [comment]
Documentado em: [formato json](https://github.com/lappis-unb/salic-ml/wiki/Protocolo-de-comunica%C3%A7%C3%A3o-entre-a-API-e-Frontend).
