### ISSUE TITLE
Adicionar mensagem de sucesso após realizar o feedback

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#164]
Atualmente após realizar o feedback a mensagem de sucesso é mostrada na index. Desta forma, ao clicar na confimação de feedback deve ser renderizado para a página de login no projeto na qual haverá a mensagem de sucesso.

**Tarefas**

- [x] Mudar rota de redirecionamento para página de login do projeto

**Critérios de aceitação:**

- [ ] Estar disponível no endereço (www.salicml.lappis.rocks/)
- [x] Ao confirmar o feedback, deve ser redirecionado para a página de login no projeto e deve ser mostrada a mensagem de sucesso.

**Comment by marlonbymendes** [comment]
Não foi valido por conta da infra do LAPPIS estar indisponível.
