### ISSUE TITLE
Remover conteúdo de métricas com informações não disponíveis 

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#165]
Por conta da métrica conter algum valor sendo ele considerado como inválido, como por exemplo: 0. Ele deixa aberto o card da métrica. O que é um comportamento indesejado! 

**Tarefas**

- [ ] Verificar o que está causando esse comportamento
- [ ] Modificar a forma como está setando a validade do valor da métrica

**Comment by victorcmoura** [comment]
O comportamento atual da aplicação executa a proposta desta issue.
