### ISSUE TITLE
Fazer o pipeline de ambiente para as aplicações

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#167]
Deve ser definido como uma issue vira um merge request, passa para o ambiente de testes internos, vai para o ambiente de homologação e finalmente chega em produção

**Tarefas**

- [ ] Definir a política de branchs
- [ ] Definir o template de um pull request

**Critérios de aceitação**

- [ ] Criar página na Wiki mostrando o processo de uma issue percorrendo as branchs e informando o que é checado nessa issue em cada etapa da política de branch
- [ ] Criar página na Wiki com o template do pull request

**Comment by victorcmoura** [comment]
A resolução das issues #229 e #230 engloba a proposta desta issue.
