### ISSUE TITLE
Definir como colocar o salic-ml no pip

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#168]
O salic-ml é usado no salic-ml-web como um pacote python sendo instalado pelo pip, porém ainda não existe uma separação das dependências de desenvolvimento para as de produção.

**Tarefas**

- [ ] Criar seções no arquivo "requirements" separando o ambiente de desenvolvimento para o de produção
- [ ] Fazer o arquivo "setup.py" ler o arquivo "requirements" para setar as dependencias de produção no pacote pip

**Critérios de aceitação**

- [ ] Arquivo requirements com as divisões das dependencias "[dev]" e "[prod]"
- [ ] Arquivo "setup.py" lendo as dependencias de produção do arquivo "requirements"
- [ ] Página na Wiki explicando como fazer o deploy no pip

**Comment by victorcmoura** [comment]
Deprecated
