### ISSUE TITLE
Razão de Itens Comuns - Evoluir notebook comparando Gaussiana com LOF

### ISSUE THREAD

**Issue by Mattioli** [lappis-unb/salic-ml#172]
Realizar estudo comparativo entre LOF e Gaussiana no contexto da métrica Razão de Itens Comuns.

**Tarefas**

- [x] Estudo da técnica LOF, verificar a viablidade desta técnica para o contexto da métrica
- [x] Detalhar resultados encontrados com o LOF
- [x] Comparar resultados do LOF com resultados da Gaussiana

**Critérios de aceitação**

- [x] Notebook disponível na `master`, comparando Gaussiana e LOF
- [x] Conclusão de qual método é o mais adequado

**Comment by RochaCarla** [comment]
@Duerno @AlexandreTK .. deixem rastreio na issue.. As tarefas foram feitas? os criterios de aceitação foram atendidos?

**Comment by Duerno** [comment]
Mas a issue não deveria ter sido fechada não, @RochaCarla. O PR ainda está aberto. PR #192
