### ISSUE TITLE
Componentizar a barra das métricas no vuejs

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#179]
A barra não está respondendo os dados da api.

**Tarefas**

- [ ] Determinar uma estratégia para poder implementar a componentização
- [ ] Implementar as barras

**Critérios de aceitação**

- [ ] Implementar a barra nas 5 métricas que precisam de barras

**Comment by victorcmoura** [comment]
Não existe mais a necessidade de se componentizar a barra no vuejs
