### ISSUE TITLE
Design Sprint - dia 01

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#18]

**Comment by Duerno** [comment]
O [resumo da reunião)[https://github.com/lappis-unb/salic-ml/wiki/Reuni%C3%A3o-27.04.18] está na wiki, pessoal.

**Comment by RochaCarla** [comment]
![photo5132187659467335648](https://user-images.githubusercontent.com/5897389/39707334-80dd45a4-51ea-11e8-8969-f53e1c78ec39.jpg)
