### ISSUE TITLE
Relatório de acompanhamento 04

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#181]
Continuação do relatório de acompanhamento das atividades da equipe (frente salicML) no período de julho 2018 à  setembro 2018

Continuação de: https://github.com/lappis-unb/salic-ml/issues/151

**Tarefas:**

- [x] Preencher as seções especificadas em: https://github.com/lappis-unb/salic-ml/wiki/Itens-para-o-relat%C3%B3rio-4---Frente-SALIC-ML-Pesquisa
- [x] Adicionar seção das limitações da Entrega 04

**Critérios de aceitação:**

- [ ]  Esta [página](https://github.com/lappis-unb/salic-ml/wiki/Itens-para-o-relat%C3%B3rio-4---Frente-SALIC-ML-Pesquisa) atualizada com as seções citadas preenchidas

**Comment by danielgs83** [comment]
Iniciei o preenchimento das seções, alguns pontos estou com pouca informação para colocar pois não estava presente naquela ação em específico, @Duerno por favor revise e complete com as suas considerações.
