### ISSUE TITLE
Refatorar os métodos de get e post da aplicação

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#182]
Atualmente, não está manutenível o rastreamento e alteração dos endpoints da API.

**Tarefas**

- [ ] Pesquisar estratégias para poder aumentar a manutenibilidade
- [ ] Analisar a viabilidade das implementações
- [ ] Implementar a melhor opção parar o contexto.

**Critérios de aceitação**

- [ ] Implementar uma forma mais robusta para a aumentar manutenibilidade de mudanças das urls dos endpoints

**Comment by victorcmoura** [comment]
Deprecated
