### ISSUE TITLE
Disponibilizar no back-end o score de complexidade de todos os projetos da Análise Financeira

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#184]
**Tarefas**

- [x] Pré calcular o score de complexidade e salvar num banco de dados
- [x] Enviar os dados pré-calculados para o front-end

**Critérios de aceitação**

- [x] Dados servidos para o front-end
- [ ] Dados disponíveis num ip público de dev
- [x] Atualizar o score de complexidade pré-calculado no banco uma vez ao dia

**Comment by victorcmoura** [comment]
Foi criada uma função que pré calcula todos os indicadores de todos os projetos. Esta função pode ser chamada por meio de um script .sh na raíz do projeto. Houve também uma configuração de um cronjob semanal (todo domingo 23h59) que executa este script .sh.

**Comment by RochaCarla** [comment]
issue fechada e a tarefa para disponibilizar no ambiente de homolog foi aberto na issue #229
