### ISSUE TITLE
Visualizar outliers no front-end ao utilizar o LOF 

### ISSUE THREAD

**Issue by AlexandreTK** [lappis-unb/salic-ml#185]
A visualização atual de outliers supõem que a detecção de outliers é baseado em Gaussiana.
Ao utilizar o modelo de LOF, as barras utilizadas atualmente podem não funcionar. Portanto, é necessário adequá-las para novos modelos de detecção de outlier.

**Tarefas**

- [ ] Pesquisar como visualizar os dados.
- [ ] Definir o que deve ser retornado por ML para que seja possível implementar a funcionalidade no front-end.
- [ ] Adicionar a funcionalidade ao front-end 

**Critérios de aceitação**

- [ ] Visualizar os outliers ao utilizar o LOF unidimensional.
- [ ] Validar com o Maia.

**Comment by victorcmoura** [comment]
Deprecated
