### ISSUE TITLE
Arquitetura: deixar de consumir salicml (pip) e passar a consumir a API (lappis-learning)

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#186]
Preparar o back-end para ser implementado na nova arquitetura proposta.

**Tarefas**

- [x] Deixar de consumir salicml (pip) e passar a consumir a API (lappis-learning)
- [x] Manipular o resultado o `.json` oriundo da API para deixar no formato especificado por #162 

**Critérios de aceitação**

- [ ] Disponível em um ambient de dev, diferente do salicml.lappis.rocks

**Comment by victorcmoura** [comment]
Alterações realizadas no nível do salic-ml-api: https://github.com/lappis-unb/salic-ml-web/commit/6f143d8c3c63332840007e1f7b1efc1d7d17130e

Por falta de disponibilidade do endpoint do lappis-learning, fiz a issue baseada em um mock do json usando o serviço https://www.mocky.io/. Por ser um mock, não marquei o critério de aceitação.

**Comment by RochaCarla** [comment]
Devido ao problema da infra do lappis na sprint, não foi disponibilizado no ambiente dev

**Comment by eduardonunes2525** [comment]
Documento contendo o [novo formato json](https://github.com/lappis-unb/salic-ml/wiki/Protocolo-de-comunica%C3%A7%C3%A3o-entre-a-API-e-Frontend).
