### ISSUE TITLE
Preparar o devops de produção para o lappis-learning

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#187]
Criar o Dockerfile e o docker-compose do ambiente de produção

**Tarefas**

- [ ] Pesquisar boas ferramentas de deploy (produção) para flask
- [ ] Criar Dockerfile de produção
- [ ] Criar docker-compose de produção
- [ ] Usar as configurações de ambiente de produção na infra do LAPPIS, no pipeline

**Critérios de aceitação**

- [ ] Disponibilizar o link do ambiente de produção no LAPPIS

**Comment by RochaCarla** [comment]
Essa issue foi realizada, mas está quebrada.. nao sabemos se foi a infra ou foi algum erro do Nginx ..

**Comment by victorcmoura** [comment]
Com a reestruturação do projeto, descrita na #295, esta issue está sendo fechada.
