### ISSUE TITLE
Criar gateway da arquitetura nova

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#189]
Fazer o serviço que consome os dados do lappis-learning e serve para o front-end os dados formatados

**Tarefas**

- [ ] Criar o projeto do gateway
- [ ] Criar os endpoint com os dados formatados para a métrica criada no lappis-learning
- [ ] Escrever testes
- [ ] Colocar no pipeline

**Critérios de aceitação**

- [ ] Pipeline rodando no gitlab
- [ ] Servir os dados formatados na infra do LAPPIS junto com o lappis-learning

**Comment by marlonbymendes** [comment]
Issue duplicada #186.
