### ISSUE TITLE
Pesquisar a quantidade de projetos criados vs quantidade de projetos finalizados no tempo

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#19]

**Comment by RochaCarla** [comment]
Gráfico:

- [ ] Eixo X: tempo (ano)

- [ ] Eixo Y:projetos criados

- [ ] Eixo Y: projetos finalizados 

Análise a ser feita:

- Utilizar como métrica de acompanhamento do fluxo de entrada/saida no salic

**Comment by LucianoPC** [comment]
Separar projetos acabados em:
- Não conseguiu capitar o sufiente,  ou não conseguiu executar
- O projeto foi executado, prestado conta e finalizado

**Comment by LucianoPC** [comment]
Enviei o e-mail para a Pauliane e para a Janete, referente as situações que indicam que um projeto foi finalizado, a Pauliane respondeu:

- Não conseguir capitar o sufuciente, ou não conseguir executar.
RESPOSTA: ORIENTO SOLICITAR INFORMAÇÕES PARA A ÁREA DA ADMISSIBILIDADE.

- O projeto foi executado, prestado conta e finalizado.
RESPOSTA: E17, E24, E25, E27, E30, E62, E68, E19, L03, L05, L06, L08, L09, 
L10 e L11.

- L03, L05, L06, L08, L10 e L11 acabaram no sentido que o projeto já 
foi analisado.
