### ISSUE TITLE
Implementar uma métrica com LOF na arquitetura nova

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#190]
**Tarefas**

- [ ] Escolher uma métrica já completa em notebook, que utiliza a ténica LOF, e atualizar o nome da issue com esta métrica.
- [ ] Determinar fontes de dados necessárias (tabelas)
- [ ] Realizar extração de features
- [ ] Aplicar LOF
- [ ] Documentação de código (docstring do python)
- [ ] Checar pipeline de integração contínua

**Critérios de aceitação**

- [ ] PR revisado e com merge com a `master`
- [ ] Métrica disponível em ambiente de dev, por exemplo: www.lappislearning.dev.lappis.rocks/metric/number_of_itens/164274

**Comment by victorcmoura** [comment]
Deprecated
