### ISSUE TITLE
Projetos com valor captado e sem nenhum outro valor

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#195]
Alguns projetos,  com complexidade 100%, 
tem apenas a métrica de valor captado. Não possuem valor aprovado (parece um grande mal cheiro), 
nem qualquer outra métrica.

Ex de pronacs com esse comportamento

-  088394
- 088057
- 070823
- 082907
- 014710

**Comment by RochaCarla** [comment]
o Pronac 161877 está corrento (tanto no salic quanto na plataforma)

**Comment by victorcmoura** [comment]
Deprecated
