### ISSUE TITLE
Documentação da complexidade financeira

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#203]
Documentar a pesquisa realizada para implementar as métricas de complexidade financeira.

**Tarefas**

- [x] Preencher as seções https://github.com/lappis-unb/salic-ml/wiki/Estimação-de-Métricas-de-Complexidade-Financeira

**Critérios de aceitação**

- [x] Toda a informação está disponível na wiki
- [x] Conteúdo revisado

**Comment by AlexandreTK** [comment]
Link na wiki:
[https://github.com/lappis-unb/salic-ml/wiki/Estimação-de-Métricas-de-Complexidade-Financeira](https://github.com/lappis-unb/salic-ml/wiki/Estimação-de-Métricas-de-Complexidade-Financeira)

**Comment by RochaCarla** [comment]
Vou atualizar alguns detalhes referentes no texto

- [ ] Mudamos o conceito de projetos problematicos para projetos complexos (a semantica muda e a interpretacao das recomendações mudam)

- [ ] Sistema de informação -> sistema de recomendação
