### ISSUE TITLE
Estudar carteira proponente

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#204]
Estudar a margem de relação do proponente com o MinC. Verificar se é possível criar o vínculo entre proponentes/fornecedores e entre fornecedores por meio do quadro societário.

Carteira de proponente - o conjunto de pessoas e CNPJs que podem ser considerados com 1 proponente.

Regra da IN:
Não pode ser usado mais de 50% do valor captado no mesmo fornecedor.

Estudar formas de extrair:

- [ ] Cruzamento de proponente com  Quadro societário de empresas (fornecedores)

**Comment by victorcmoura** [comment]
Estudo sendo realizado em repositório privado.
