### ISSUE TITLE
Review 01/10/2018

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#206]
Atualização do status da review metade da sprint.

Atualizar nos comentários:

- [ ] Número das issues fechadas (se teve processo de PR + validação) 

- [ ] Status das issues remanescentes (registrar problemas encontrados, se necessário, issues novas abertas)

- [ ] Registrar alguma dificuldade/impedimento para conseguir fechar todas as issues alocadas pra cada membro essa semana (até o final da sprint)

**Comment by victorcmoura** [comment]
https://github.com/lappis-unb/salic-ml/issues/184 - Disponibilizar no back-end o score de complexidade de todos os projetos da Análise Financeira

- Existe um script que, ao ser executado, pré calcula as complexidades de todos os projetos (Este processo está demorando cerca de 30min).
- Tomei a liberdade de incluir a issue https://github.com/lappis-unb/salic-ml/issues/183 (Ordenar todos os projetos da Análise Financeira por complexidade financeira) do @eduardonunes2525 no processo de desenvolvimento desta feature pois consistia apenas em descomentar 3 linhas no html da index.
- Ainda falta criar um cronjob para executar tal script semanalmente (A issue menciona que o cálculo deve ser feito 1x ao dia. Isso travaria o sistema por 30min todos os dias). Acredito que se realizarmos o cálculo semanalmente, não haverá prejuízo relevante e teremos um uptime melhor.

https://github.com/lappis-unb/salic-ml/issues/186 - Arquitetura: deixar de consumir salicml (pip) e passar a consumir a API (lappis-learning)

- Issue ainda não iniciada.

https://github.com/lappis-unb/salic-ml/issues/150 - Preparar reunião estratégica 28/09

- Dei uma olhada nos slides antes da reunião e não encontrei algo que estivesse faltando.
- Participei da reunião.
- Conversei brevemente com o @danielgs83, @AlexandreTK, @Mattioli e @LucianoPC agora de tarde para repassar o que foi discutido.

https://github.com/lappis-unb/salic-ml/issues/181 - Relatório de acompanhamento 04

- Issue ainda não iniciada

**Comment by Mattioli** [comment]
#175 - Valor Captado - Evoluir notebook LOF
PR aberto, esperando revisão. Conversando com o @danielgs83, vimos que alguns parâmetros da métrica LOF estavam mal calibrados. Assim, todas as métricas de LOF 'fechadas' vão ter que passar por um review técnico para ajustar esse parâmetros.

#176 - Novos Fornecedores - Evoluir notebook LOF
Só falta o ajuste da LOF descrito no último parágrafo

#174 Preços dos Itens - Evoluir notebook LOF
Não iniciada

**Comment by marlonbymendes** [comment]
#155 - O desafio atual agora é não realizar conexão com a VPN durante os testes unitários no GitlabCI. Entretanto, no ambiente de dev (docker-compose) procura-se uma solução que seja execute testes unitários sem conexão com VPN mas que funcione normalmente os endpoints com conexão com API. No demais, os outros critérios de aceitação já foram alcançados.

#190 - Issue ficou como menor prioridade na sprint e por enquanto não foi iniciada.

**Comment by eduardonunes2525** [comment]
#160 - Finalizada
#164 - Finalizada
#178 - Finalizada
#180 - Finalizada
#183 - Semi-Finalizada -> Falta validação do Rodrigo Maia
#162 - Em andamento -> Falta documentação e ajusto dos nomes dos atributos dos objetos.
#179 - Em andamento -> Estou tendo dificuldade em criar uma lógica que generalize a criação da barra.
#182 - Não iniciada

**Comment by AlexandreTK** [comment]
#149 - Encontrar contra exemplos que evidencie a limitação atual do ML
Finalizada. Link para wiki esta na issue.

#177 - Valor Comprovado - Evoluir notebook comparando Gaussiana com LOF
Finalizada e já está na master. Mas enviarei um novo PR com novas alterações sugeridas pelo Daniel.

#173 - Projetos do Proponentes - Evoluir notebook comparando Gaussiana com LOF
Finalizada e já está na master. Mas enviarei um novo PR com novas alterações sugeridas pelo Daniel.

#172 - Razão de Itens Comuns - Evoluir notebook comparando Gaussiana com LOF
O Duerno estava trabalhando nessa issue, está aplicando revisões do Daniel.

#203 - Documentação da complexidade financeira
Esperando validação. Link para wiki esta na issue.
