### ISSUE TITLE
Encontrar a quantidade média de diligências por projeto

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#21]

**Comment by RochaCarla** [comment]
Por que não o histograma de quantidade de diligencias por projeto?

**Comment by RochaCarla** [comment]
- [ ] Métrica: Quantas vezes uma diligencia é tramitada (envio de diligencia, resposta, contra resposta,  até fechar a diligencia). 

- [ ] Tempo de diligencia (desde ela ser aberta até ser fechada) - tudo histogramas

- [ ] Varia de acordo com o projeto? (tamanho, segmento do projeto, quantidade de itens, etc)

**Comment by LucianoPC** [comment]
No banco de dados do Salic tem diligências com data de resposta anterior a data de solicitação, como por exemplo a diligência com idDiligencia = 31323.

Pode ser interessante conferir as seguintes informações:
- [ ] Checar se as diligencias com data resposta anterior a data de solicitação ocorreram em um período de tempo
- [ ] Checar se essas diligências estão em um mesmo projeto

**Comment by marlonbymendes** [comment]
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by marlonbymendes** [comment]
A "área" e o "segmento" de um projeto estão nas seguintes tabelas:

| Campo | Tabela no banco |
| ------------- |:-------------:|
| Área | SAC.dbo.Projetos.Area<br> SAC.dbo.Area |
| Segmento | SAC.dbo.Projetos.Segmento<br> SAC.dbo.Segmento |

**Comment by marlonbymendes** [comment]
Há ocorrências de linhas com idPronac = 0 na tabela SAC.dbo.tbDiligencia. Remover estas ocorrências da análise.

**Comment by RochaCarla** [comment]
Está super legal os resultados preliminares.
Duvidas: total de projetos é total de IDs pronacs ou é a quantidade de projetos executados (para a análise faz mais sentido ser a ultima ). Podem deixar explicito o significado das variáveis?

**Comment by marlonbymendes** [comment]
@RochaCarla qual lugar você acha que fica melhor pra visualizar estas definições, no próprio notebook?
Segue uma definição inicial:

| Variável | Definição |
| ------------- |:-------------:|
| Total de projetos | Número de idPronac distintos na tabela SAC.dbo.Projetos. <br> Cada projeto no SALIC tem exatamente um idPronac |
| Projetos com pelo menos uma diligência | Projetos que tem pelo menos uma linha (diligência) na tabela diligencia. Para cada diligência é associado um idPronac do projeto relacionado |
