### ISSUE TITLE
Documentar o fluxo da  Estimativa de métricas complexidade financeira

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#216]
Detalhar os algoritmos utilizados na estimação das métricas de complexidade financeira, e os dados do banco de dados utilizados.

Refinar o documento [https://github.com/lappis-unb/salic-ml/wiki/Estimação-de-Métricas-de-Complexidade-Financeira](https://github.com/lappis-unb/salic-ml/wiki/Estimação-de-Métricas-de-Complexidade-Financeira)

**Tarefas**

- [x] Detalhar  os campos no banco de dados utilizados

- [x] Detalhar os algoritmos de como calcular os outlier

- [x] Disponibilizar os links para os notebooks

**Critérios de aceitação**

- [ ] Documentação completa, no qual qualquer membro da equipe seja capaz de reproduzir/compreender o trabalho realizado

**Comment by AlexandreTK** [comment]
Tarefas adicionadas ao tópico "Detalhes da solução" no fim do documento.
