### ISSUE TITLE
SarauML - Complexidade Proponente / fornecedores

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#217]
Realizar um sarau/workshop para levantar as hipóteses para serem validados em relação ao proponente/fornecedores

**Tarefas**

- [ ] Levantar quais os dados disponíveis referentes aos proponentes

- [ ] Levantar quais dados disponíveis referentes aos fornecedores

- [ ] Definir dia/hora do sarau

- [ ] Levantas as hipóteses

**Critérios de aceitação**

- [ ] O sara foi realizado

- [ ] Os resultadeos obtidos foram registrados

**Comment by danielgs83** [comment]
Proposta de data para o sarau: dia 29/10/2018, das 14h às 17h.

**Comment by victorcmoura** [comment]
Dados os estudos realizados desde a abertura desta issue e os resultados obtidos, demonstrando que encontramos os dados relevantes para a análise de relação entre os papeis presentes no pipeline de incentivo cultural (relação de sociedades, possibilidade de se analisar o fluxo financeiro dos projetos culturais...), esta issue está sendo fechada.
