### ISSUE TITLE
Deixar de consumir .csv e passar a consumir o banco de dados do SALIC

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#219]
Atualmente os dados utilizados pelo ML são oriundos de arquivos `.csv`. É necessário ter acesso aos dados por uma conexão direta com o banco de dados em vez de utilizar arquivos. 

**Tarefas**

- [x] Configurar container VPN
- [x] Executar queries SQL no banco
- [x] Criar DataFrames a partir dos resultados das Queries SQL
- [ ] Atualizar o pacote salicml no pip
- [ ] Validar integração com o salic-ml-web

**Critérios de aceitação**

- [x] ML não ter dependência de arquivos `.csv` ou similares
- [x] DataFrames construidos a partir de queries no banco do SALIC
- [ ] Pacote estar no pip
- [ ] Garantir que o novo pacote não quebra o salic-ml-web

**Comment by marlonbymendes** [comment]
Longo tempo de execução para obter dados comprovados de um projeto: https://github.com/lappis-unb/salic-ml/issues/233

**Comment by Duerno** [comment]
O código não está otimizado e precisa de refatoração (acesso ao banco é feito em cada métrica, flake8 e pytest não foram verificados), contudo, esse código não será utilizado na futura arquitetura e, por isso, optou por não gastar muito tempo com esse PR, que será aceito mesmo sem as otimizações.

**Comment by victorcmoura** [comment]
A integração com o salic-ml-web não foi possível por erros no código do pacote. Alguns foram resolvidos com commits de hotfix (inserção de __init__.py faltante, por exemplo) mas há um que não era tão trivial de resolver. O módulo de conexão com o banco faz uso de um pacote chamado "exceptions", que deveria estar dentro da pasta core, mas não está (pelo menos na branch master).

**Comment by marlonbymendes** [comment]
O problema do `exceptions` aparentemente foi resolvido com https://github.com/lappis-unb/salic-ml/pull/248.

**Comment by victorcmoura** [comment]
Após tentativa de integração, não consegui consumir o pacote como antes. Ainda há a necessidade de se investigar o problema para saber se ocorreu do lado do salic-ml ou do lado do salic-ml-web. A issue será fechada e outra será aberta para contemplar a etapa de integração. A nova issue é: #258
