### ISSUE TITLE
Conseguir acesso (leitura) ao banco de Produção

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#226]
Atualmente o acesso ao banco através da VPN está conectando com o banco de homologação, que é uma cópia atrasada do banco de produção. É necessário ter acesso ao banco de produção do SALIC.

**Tarefas**

- [ ] Comunicar com as pessoas que podem conceder este acesso
- [ ] Configurar uma nova VPN (se necessário)

**Critérios de aceitação**

- [ ] Dados obtidos diretamente do banco de produçãp

**Comment by RochaCarla** [comment]
Conversei com o Marcus da CGTIC, e ele ficou de marcar uma reunião para definir como será esse acesso.

**Comment by Duerno** [comment]
Hoje, eu, Maia e Moura conversamos com o Leonardo Bites (coordenador técnico da CGTEC) e concordamos que:
1. CGTEC vai entregar um acesso à uma versão somente leitura do BD em mais ou menos 1 mês;
2. Seguimos usando o BD de homologação.

**Comment by victorcmoura** [comment]
Issue ainda em aberto

**Comment by rodmaia2099** [comment]
Trasnferida para #325
