### ISSUE TITLE
Utilizar apenas projetos que já estão ou passaram na Análise Financeira

### ISSUE THREAD

**Issue by AlexandreTK** [lappis-unb/salic-ml#227]
Utilizar tanto no ML como backend apenas projetos que já estão ou passaram pela Análise Financeira.

**Tarefas**

- [x] Construir filtro de acordo com o que foi comentado com o Rômulo para identificar se o projeto está ou já passou pela análise financeira.
 - [x] Filtrar os projetos utilizados pelo treinamento de ML.
 - [ ] Filtrar os projetos no Backend.

**Critérios de aceitação**

- [x] Ambiente de dev com os filtros.
- [x] Filtros para ML na master / datasets atualizados.

**Comment by marlonbymendes** [comment]
Possível solução: https://github.com/lappis-unb/salic-ml/issues/240#issuecomment-433395993

**Comment by danielgs83** [comment]
Issue fechada pois foi aberta issue #240 para mapear o problema via query no banco.
