### ISSUE TITLE
 Colocar mensagem de sucesso após realizar o feedback em homologação

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#228]
Atualmente após realizar o feedback a mensagem de sucesso é mostrada na index. Desta forma, ao clicar na confimação de feedback deve ser renderizado para a página de login no projeto na qual haverá a mensagem de sucesso. 
Issue  #164 terminou, mas faltou colocar em homolog (problema da infra do lappis)

**Tarefas**

- [x] Mudar rota de redirecionamento para página de login do projeto

**Critérios de aceitação:**

- [ ] Estar disponível no endereço (www.salicml.lappis.rocks/)
- [x] Ao confirmar o feedback, deve ser redirecionado para a página de login no projeto e deve ser mostrada a mensagem de sucesso.

**Comment by eduardonunes2525** [comment]
Foi finalizada! Porém por não haver mais a necessidade de utilização da mesma por ter sido descontinuado a versão do monolítico a issue está sendo fechada.
