### ISSUE TITLE
Disponibilizar em homolog o score de complexidade de todos os projetos da Análise Financeira 

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#229]
Tarefas realizadas na issue #184 mas falta colocar em ambiente de homolog (nao foi colocado por problema na infra)

**Critérios de aceitação**

- [x] Dados servidos para o front-end
- [x] Dados disponíveis num ip público de dev
- [ ] ~Atualizar o score de complexidade pré-calculado no banco uma vez ao dia~

**Comment by victorcmoura** [comment]
Por conta da reestruturação dos repositórios, os itens, que haviam sido concluídos previamente, estão sendo marcados como não resolvidos.

**Comment by victorcmoura** [comment]
Dado que a API foi colocada em ambiente de homolog em uma máquina no lappis e que o front está disponível no [github.io](https://lappis-unb.github.io/salic-ml-frontend/#/), esta issue está sendo fechada.
