### ISSUE TITLE
Disponibilizar em ambiente de homolog métrica de números de itens na arquitetura proposta

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#230]
Apresentar a viabilidade técnica da arquitetura proposta. Todas as tarefas foram realizadas na issue #155, faltou disponibilizar em ambiente de homologação por problema na ifra

Tarefa:

- [x] IP públic no ambiente de dev , acessível pelo browser, que forneça a resposta (.json) para qualquer PRONAC dado

**Comment by victorcmoura** [comment]
Pelo mesmo problema com a #229, esta issue não está sendo fechada.

**Comment by victorcmoura** [comment]
Dado que a API teve seu deploy concluído em ambiente de homolagação, esta issue está sendo fechada.
