### ISSUE TITLE
Arquitetura: deixar de consumir salicml (pip) e passar a consumir a API (lappis-learning) em homolog

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#231]
Preparar o back-end para ser implementado na nova arquitetura proposta. issue finalizada em #186 mas faltou colocar disponivel em ambiente de dev, pelo problema da infra

**Critérios de aceitação**

- [ ] Disponível em um ambient de dev, diferente do salicml.lappis.rocks

**Comment by victorcmoura** [comment]
Por conta da reestruturação dos repositórios (#295), esta issue não é mais necessária.
