### ISSUE TITLE
Conexão com o banco está utilizando 4x a mais de memória do que o tamanho final do .csv

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#234]
A planilha orcamentaria em disco ocupa aproximadamente `450 MB`. Ao fazer o download desta planilha, utilizando a conexão direta com o banco de dados, existe um pico no uso de memória que chega a `2500 MB` aproximadamente. Depois do download terminar, o uso de memória volta ao esperado (`450 MB`), porém o pico no uso de memória é preocupante.

**Comment by victorcmoura** [comment]
Issue englobada na #293
