### ISSUE TITLE
Verificar os dados de CNPJ/CPFs 

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#239]
Verificar se os dados no banco disponibilizam os CNPJ de empresas e os socios dessas empresas (CPFs). Banco:

**Tarefas**

- [x] Acesso à tabela SAC.scCGU.tbProponentePJxSocios
- [x] Para cada CNPJ, deve haver um conjunto de CPFs associados

**Critérios de aceitação**

- [x] Notebook privado disponível no gitlab para acesso aos dados

**Comment by marlonbymendes** [comment]
O pull request (merge request) foi aberto no gitlab: [link](https://gitlab.com/lappis-unb/salic-ml-data/merge_requests/1) por conta da sensibilidade dos dados. Caso o revisor aceite o PR, por favor fechar esta issue.

**Comment by RochaCarla** [comment]
Fiquei em dúvida sobre se teria a mesma informação sobre os fornecedores (se para cada fornecedor - CNPJ teria a lista de sócios)?
