### ISSUE TITLE
Extração e análise de features textuais dos projetos culturais

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#243]
Extrair features textuais a partir de todos os dados textuais (curtos e longos), como descrição, título, itens, objeto e etc, de projetos culturais.

**Tarefas**

- [x] Mapear quais são os dados textuais de projetos culturais
- [x] Remover projetos que ainda não chegaram à etapa de análise financeira
- [ ] Agrupar projetos por segmentos/produtos culturais
- [x] Extrair a maior quantidade possível de features textuais a partir dos dados, utilizando, por exemplo, TD-IDF, bag-of-words, word2vec, word-clouds e etc
- [ ] Analisar a relação entre as features extraídas

**Critérios de aceitação**

- [x] Ter um notebook com a pesquisa no repositório
- [x] Apresentar resultados e conclusões da pesquisa
- [x] Ser capaz de visualizar todas as features do projeto

**Comment by RochaCarla** [comment]
Essa issue está muito complexa, não parece que dá pra ser feito em uma única sprint. Sugestão: detalhar a issue com as atividades para serem feitas no timebox da sprint

**Comment by victorcmoura** [comment]
Trabalho iniciado, porém não é prioridade no momento. Decidiu-se que a issue será fechada e, caso necessário, outra será aberta
