### ISSUE TITLE
Pesquisa: similaridade de projetos, levando em conta dados financeiros

### ISSUE THREAD

**Issue by Mattioli** [lappis-unb/salic-ml#244]
Realizar pesquisa para a determinação da similaridade de projetos em relação aos dados da análise financeira.

Para mais detalhes, consultar: [Um algoritmo de detecção de similaridade de projetos Roadmap](https://github.com/lappis-unb/salic-ml/wiki/Um-algoritmo-de-detec%C3%A7%C3%A3o-de-similaridade-de-projetos---Roadmap)

**Tarefas**

- [x] Exploração dos dados
- [x] Preparar os datasets
- [x] Realizar engenharia de features
- [x] Definir a função de distância entre dois vetores multidimensionais de features
- [x] Definir um algoritmo de busca para encontrar os K projetos mais similares, para um dado projeto
- [ ] Consultar trabalhos similares já desenvolvidos neste repositório

**Critérios de aceitação**

- [x] Função de distância definida
- [x] Algoritmo de busca definido
- [ ] Um notebook disponível na master contendo as análises realizadas e seus resultados

**Comment by Mattioli** [comment]
Considerar o conjunto de fornecedores dos projetos como features.

**Comment by marlonbymendes** [comment]
Segundo o feedback de um técnico sobre a aplicação em homologação, considerar o tempo de execução dos projetos para encontrar projetos similares é relevante:

"esta informação é util para a análise do cumprimento do objeto porque há a possibilidade do proponente fazer uma "clonagem" dos projeto, sendo assim, é importante verificarmos se há outros projeto semelhantes sendo executados em mesmo período. Contudo, registro que esta informação já consta no Salic, pois lá podemos pesquisar os projetos pelo CNPJ, inclusive de forma mais completa, já que mostra em qual situação os projetos se encontram." (Feedback no banco de dados)

**Comment by Mattioli** [comment]
Levando em conta o [comentário](https://github.com/lappis-unb/salic-ml/pull/254#pullrequestreview-171550328) do @danielgs83, uma nova issue foi aberta para fazer os refinamentos requisitados.
