### ISSUE TITLE
Detecção de similaridade baseada em features textuais

### ISSUE THREAD

**Issue by Duerno** [lappis-unb/salic-ml#245]
Pesquisar e implementar algoritmos de detecção de similaridade entre projetos culturais, utilizando os resultados da issue #243

**Tarefas**

- [ ] Pesquisar funções de distância/similaridade entre projetos (matriz de similaridade, KNN e etc)
- [ ] Dado um projeto específico, criar ranking de projetos similares

**Critérios de aceitação**

- [ ] Ter um notebook com a pesquisa no repositório
- [ ] Apresentar resultados e conclusões da pesquisa

**Comment by Duerno** [comment]
O PR #253 implementa, além da extração de features textuais de projetos culturais, um detector de similaridade, satisfazendo as tarefas e os critérios de aceitação desta issue.

**Comment by victorcmoura** [comment]
A discussão sobre features textuais realizada na época da criação desta issue não representa o contexto atual do projeto
