### ISSUE TITLE
Ajustar algoritmo que filtra projetos que estão na Análise Financeira no front do ML

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#246]
Atualmente o algoritmo utilizado possui algumas limitações conhecidas, entretanto a informação da fase do projetos está disponível no banco, conforme este [comentário](https://github.com/lappis-unb/salic-ml/issues/240#issuecomment-433395993).

**Tarefas**

- [ ] Validar queries do comentário citado
- [ ] Ajustar algoritmo para utilizar a query do comentário

**Critérios de aceitação**

- [ ] Exibir projetos apenas da Análise Financeira, segundo uma query validada

**Comment by victorcmoura** [comment]
Deprecated
