### ISSUE TITLE
Ajustar algoritmo que filtra projetos que estão na Análise Financeira no ML

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#247]
Atualmente o algoritmo utilizado possui algumas limitações conhecidas, entretanto a informação da fase do projetos está disponível no banco, conforme este [comentário](https://github.com/lappis-unb/salic-ml/issues/240#issuecomment-433395993).

**Tarefas**

- [ ] Validar queries do comentário citado
- [ ] Filtrar nos datasets projetos que já estão na análise financeira ou posterior

**Critérios de aceitação**

- [ ] Utilizar no treinamento apenas projetos que estão na análise financeira ou posterior

**Comment by victorcmoura** [comment]
Deprecated
