### ISSUE TITLE
Métrica Quantidade de comprovantes por código da operação

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#249]
A métrica que mais reflete a complexidade de avaliação financeira para os técnicos da SEFFIC é a quatidade de comprovantes por código da operação. O código da operação refere à origem do pagamento para aquele comprovante (número do cheque, número da transferência, numero do saque). Se uma operação (por exemplo um cheque) é usado para justificar mais de um comprovante, isso insere uma complexidade de análise (o técnico da Sefic tem que fazer o batimento/soma dos comprovantes com o valor da operação).

**Tarefas**
- [ ] Levantar a quantidade de comprovantes por operação de um projeto cultural
- [ ] Levantar a complexidade dessa métricas (qual a porcentagem/ quantidade de absoluta de código de operacoes possuem mais de um comprovante)
- [ ] Listar código de operações com mais de um comprovante, agrupado por tipo de operação (cheque, transferência ou saque)
- [ ] Indicar se é outlier e a "porcentagem"
- [x] Investigar disponibilidade dos dados

**Critérios de aceitação**
- [x] Notebook com estudo e implementação da métrica para um determinado segmento cultural
- [ ] `.json` disponível num link/ip de pro produção
- [ ] O técnico da SEFIC é capaz de saber a complexidade financeira a partir dessa métrica
- [ ] O técnico da SEFIC é capaz de acessar os comprovantes que possuem o mesmo codigo de operação

**Comment by Mattioli** [comment]
Fazendo uma busca pelo banco de dados, não foi encontrado pra um dado comprovante/item as identificações referente ao(s) código(s) de operação que foram utilizados para pagamento do mesmo. De qualquer forma, foi subido na branch op_code_receipts um notebook que simula a existência da identificação e realiza as operações básicas de agrupamento por ids de código de operação. Assim que a localização das identificações dos códigos de operações forem descobertas no banco de dados, é fácil finalizar a issue com algumas alterações.

**Comment by victorcmoura** [comment]
Issue englobada na #262
