### ISSUE TITLE
Metrica complexidade fornecedor

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#252]
Concentração de itens: fornecedor pode concentrar até 50% do valor captado; proponente pode fornecer para ele mesmo até 50% do valor captado. (exceção: declarar CNPJ do proponente como Corpos estáveis ou grupo familiar que podem concentrar mais de 50%).  Problema: para cada CPF (CNPJ) calcular sua carteira  (quanto está sendo pago) no contexto do projeto. 

**Tarefas**

- [ ] Levantar as relações entre CPFs e CNPJ

- [ ] Calcular o valor pago para cada fornecedor e o percentual que ele representa no projeto

**Critérios de aceitação**

- [ ] Notebook com estudo e implementação da métrica para um determinado segmento cultural

**Comment by victorcmoura** [comment]
Os estudos relacionados aos CPFs/CNPJs estão sendo feitos em um repositório privado
