### ISSUE TITLE
Integrar SALICML com o SALIC em produção

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#255]
No dia 25/10 (Quinta-feira), foi realizado uma reunião para que fosse discutido como seria a integração da API desenvolvida pelo LAPPIS com a aplicação do SALIC. Estavam presentes na reunião: Decko, representante do laboratório da UFABC. Eduardo Nunes e Victor Moura, representantes do LAPPIS.

Houve a apresentação da API desenvolvida e foram sugeridas duas abordagens de integração.
* A primeira abordagem é que os desenvolvedores do laboratório da UFABC teriam a liberdade de desenvolver um frontend próprio que consumisse a API e inserissem isso no SALIC.

* A segunda abordagem é reaproveitar o protótipo desenvolvido pelo LAPPIS, em Vuejs, visando a diminuição da complexidade na hora da integração com o SALIC, uma vez que, o SALIC é desenvolvido nesta tecnologia.

Porém, ambas as abordagens foram consideradas inadequadas pelo representante da UFABC. Da parte do mesmo, foi sugerido que poderia haver disponibilidade de um desenvolvedor para que auxiliasse os desenvolvedores do LAPPIS à realizarem a integração no SALIC. Após não haver um consenso entre as partes, a reunião foi encerrada sem que houvesse um planejamento para a integração.

**Comment by rodmaia2099** [comment]
Após nova conversa com a liderança da CGTEC, ficou decidido que faremos um novo planejamento uma vez que a equipe CGTEC disponibilize um BD separado para o ML não onerar o ambiente de produção do SALIC.

**Comment by rodmaia2099** [comment]
As tarefas desta issue serão evoluídas em #306
