### ISSUE TITLE
Refinar pesquisa de similaridade de projetos, levando em conta dados financeiros

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#257]
O comentário https://github.com/lappis-unb/salic-ml/pull/254#pullrequestreview-171550328 indica possíveis ajustes a pesquisa citada, os quais precisam ser feitos para que o https://github.com/lappis-unb/salic-ml/pull/254 seja aceito.

**Tarefas**

- [x] Calcular matriz de similaridade entre 100 projetos aleatórios
- [x] Selecionar 10 pronacs (verificar com a Carla), procurar os 2 projetos mais similares com estes 10 selecionados
- [ ] Pesquisar e justificar quais tipos de projetos devem estar na selação dos pronacs citados na tarefa acima em relação ao comentário https://github.com/lappis-unb/salic-ml/pull/254#pullrequestreview-171550328

**Critérios de aceitação**

- [x] Ajustes sugeridos implementados
- [ ] Um notebook disponível na master contendo as análises realizadas e seus resultados

**Comment by marlonbymendes** [comment]
Possíveis PRONACs para comparação: 

-http://versalic.cultura.gov.br/#/proponentes/b1920ede92745e0f2ac44393feb5e0081bfdd79abb89a893b73196837995

- http://versalic.cultura.gov.br/#/proponentes/b87ac883122eb525d6df6d7233091fe412dcc59e22b579f7c5caedcb8c5e

**Comment by rodmaia2099** [comment]
Revisei o notebook disponível (aqui)[https://github.com/lappis-unb/salic-ml/blob/2e029c6e099fa66ebd85849f928e77e6204fd71a/notebooks/doing/projects_similarity_feature_engineering.ipynb]. Notei que é possível um **projeto A**, que captou recursos, ser mais semelhante a um **projeto B**, que não captou, do que a um **projeto C** que captou. Exemplo: tabela de resultados para PRONAC 132200.

Deveríamos eliminar projetos que não foram executados? Provoco a reflexão porque *na vida real* um projeto que não captou/executou é só um plano, uma vontade. Logo, tirar outras conclusões com base nessa similaridade poderia resultar em viés.
