### ISSUE TITLE
Fazer integração do pacote salic-ml e o salic-ml-web

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#258]
Após a troca (https://github.com/lappis-unb/salic-ml/issues/219) de consumo de arquivos `.csv` para consumir o banco do SALIC, a integração entre o pacote do salic-ml e o salic-ml-web está instável. Investigar esta instabilidade.

**Tarefas**

- [ ] Investigar motivo da instabilidade
- [ ] Integrar

**Critérios de aceitação**

- [ ] Todas as features anteriores continuarem funcionando
- [ ] Manter a performance

**Comment by victorcmoura** [comment]
Deprecated
