### ISSUE TITLE
Quantidade de comprovantes por código de operação

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#262]
Consultar a issue a #249 para detalhamentos do backend.

**Tarefas**

- [x] Definir explicitamente o formato `.json`
- [x] Listar código de operações com mais de um comprovante, agrupado por tipo de operação (cheque, transferência ou saque)
- [ ] ~Implementar em componentes do Vuejs~
- [ ] ~Discriminar outliers~

**Critérios de aceitação**

- [x] Conseguir identificar projetos que tenham mais de um comprovante por código de operação (no notebook)

**Comment by victorcmoura** [comment]
Falta revisar com dados reais. A issue foi implementada com dados mockados. Assim que o ML + Gateway fornecerem os dados, isso será possível.

**Comment by victorcmoura** [comment]
A implementação desta métrica ainda não foi finalizada. Issue permanece aberta

**Comment by fabiolamfleury** [comment]
Na tentativa de se avaliar a viabilidade dessa métrica, tentou-se primeiramente organizar uma métrica de comprovantes por projeto, e quantos itens orçamentários que estão associados por comprovante

**Comment by fabiolamfleury** [comment]
Foram mapeadas colunas que guardam informações sobre os comprovantes de pagamento, apesar de ser um dado não fornecido por todos os projetos ( o tipo de forma de pagamento).
Na tabela BDCorporativo.scSAC.tbComprovantePagamento, foram mapeados dois campos, que são tiny int e parecem ser apresentados em forma de texto no versalic.

- tpDocumento : Encontrados valores como 2, 3, 4 e 5
- tpFormaDePagamento: 0, 1 , 2, 3

Tipo do documento: Guia de Recolhimento    Forma de pagamento: Saque/Dinheiro

Tipo do documento: Cupom Fiscal  Forma de pagamento: Transferencia Bancaria

**Comment by fabiolamfleury** [comment]
Issue retomado por ter terminado as issues de fato da sprint

**Comment by fabiolamfleury** [comment]
Atividades que devem ser realizadas em relação a essa issue
- Revisar as informações do notebook
- Validação dos SQLs: foi referenciada na issue #240

**Comment by fabiolamfleury** [comment]
As informações foram realizadas em pr aberto
