### ISSUE TITLE
Relatório de entrega 05

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#264]
Fazer o relatório de acompanhamento do trabalho realizado pela equipe entre outubro 2018 - Dezembro 2018.

Data limite para entrega: 01/12
**Tarefas**

- [x] Listar as principais funcionalidades desenvolvidas no período

- [x] Descrever, de forma sucinta, os principais objetivos da equipe no período

- [x] Linkar documentação da wikii relacionada às atividades identificadas nas tarefas acima

**Critérios de aceitação**

- [x] Ter uma página markdown com o conteúdo

- [x] O conteúdo refletir o trabalho realizado no período

**Comment by RochaCarla** [comment]
Produtos prometidos para essa entrega

- plano de entrega contínua
- relatorio de monitoramento/melhoria das métricas

**Comment by danielgs83** [comment]
Página markdown iniciada na wiki: https://github.com/lappis-unb/salic-ml/wiki/Itens-para-o-relat%C3%B3rio-5-Frente-SALIC-ML-Pesquisa

**Comment by victorcmoura** [comment]
Dado que a entrega foi realizada e o documento apresenta os itens indicados como critérios de aceitação, esta issue está sendo fechada.
