### ISSUE TITLE
Gerar Releases -- e releases notes

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#265]
Criar a cultura/habito de criar releases, com releases notes das principais entregas

**Comment by victorcmoura** [comment]
Release referente à versão entregue para produção em https://salicml.lappis.rocks (API) foi lançada: https://github.com/lappis-unb/salic-ml-web/releases/tag/0.2

**Comment by victorcmoura** [comment]
Deprecated
