### ISSUE TITLE
Melhorar documentação dos endpoints da API

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#267]
Atualmente, há documentação. Porém, a mesma não apresenta um padrão e é insuficiente para entender os dados apresentados na API.

**Tarefas**

- [ ] Reconfigurar o swagger.
- [ ] Estabelecer padrão de documentação.

**Critérios de aceitação**

- [ ] Estar disponibilizado em: https://salicml.lappis.rocks/ .

**Comment by victorcmoura** [comment]
Done
