### ISSUE TITLE
Refinar frontend da aplicação 

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#274]
Com base no [feedback recebido da SEFIC ](https://github.com/lappis-unb/salic-ml/wiki/Reuni%C3%A3o-2018.11.22) precisamos ajustar a apresentação das métricas

**Tarefas**
- [x] Remover *Itens orçamentários inesperados*
- [x] Remover *Preços acima da média*
- [x] Remover *Valor aprovado*
- [x] Substituir *Valor captado* e *Valor comprovado* por *Valor a ser comprovado*
- [x] Em *Projetos por proponente*, combinar as colunas de data em uma única coluna Período de execução que mostre apenas das datas de início e fim, sem horários
- [x] Renomear *Comprovantes com preço acima de 50%* para *Comprovantes com extrapolação acima de 50% do aprovado*
- [x] Ordenar métricas pelo peso que tem no score total
- [x] Mostrar o score total como um número absoluto

## Valor a ser Comprovado (Mapeado na issue: #292)
- [ ] Em *Valor a ser comprovado*, exibir a lista de itens orçamentários que não foram comprovados

## Projetos por proponente (Mapeado na issue: #291)
- [ ] Em *Projetos por proponente*, combinar as colunas Etapa e Situação em uma nova coluna Situação que mostre apenas o código da situação (E24, K00) e que indique o rótulo da etapa mais o rótulo da situação no tooltip da célula

## Comprovantes de pagamento (Mapeado na issue: #290)
- [ ] Separar *Comprovantes de pagamento* em três métricas separadas: *Comprovantes por Transferência*, *Comprovantes por Saque* e *Comprovantes por Cheque*
- [ ] Em *Comprovantes por Transferência*, acrescentar um link para as relações de pagamento do projeto
- [ ] Em *Comprovantes por Saque*, acrescentar um link para as relações de pagamento do projeto
- [ ] Em *Comprovantes por Cheque*, acrescentar um link para as relações de pagamento do projeto

## Novas issues
- [ ] Incluir nova métrica de  *Etapas de custo vinculado com extrapolação acima do permitido*
- [ ] Substituir links para itens orçamentários individuais por um link para a planilha orçamentária, segundo [a regra de qual planilha usar](https://github.com/lappis-unb/salic-ml/wiki/Reuni%C3%A3o-2018.11.22#links-do-salic)

**Critérios de aceitação**

- [ ] Nova página de diagnóstico está de acordo com as solicitações dos técnicos das SEFIC

**Comment by victorcmoura** [comment]
Dado que as pendências foram transferidas para outra issue, esta está sendo fechada.
