### ISSUE TITLE
Nova feature - Numero de Itens não comprovados por projeto

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#276]
Esta feature visa refletir a complexidade de análisar um projeto: quanto mais itens não comprovados, maior a complexidade daquele projeto

**Tarefas**

- [ ] Investigar disponibilidade dos dados
- [ ] Pesquisar a distribuição de itens não comprovados por projeto
- [ ] Implementar método de classificar outliers nesta feature
- [ ] Validar notebook

**Critérios de aceitação**

- [ ] Notebook validado
- [ ] Notebook disponível na master

**Comment by victorcmoura** [comment]
Deprecated
