### ISSUE TITLE
Definir como a métrica projetos do mesmo proponente influencia no cálculo do score global

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#278]
Atualmente, a métrica "Projetos do mesmo proponente" não influencia no cálculo do score global do projeto. O problema envolvido na influência é o cálculo recursivo da complexidade, onde todos os projetos são influenciados pelo cálculo do seu próprio score global.

**Tarefas**

- [ ] Levantar possíveis soluções para o problema
- [ ] Decidir qual a solução mais viável

**Critérios de aceitação**

- [ ] Deve haver uma solução selecionada
- [ ] A solução selecionada não pode apresentar comportamento recursivo

**Comment by rodmaia2099** [comment]
@victorcmoura a gente já não tinha decidido que ia considerar apenas o histórico de projetos anteriores ao projeto "selecionado" para evitar a recursidividade?

**Comment by victorcmoura** [comment]
@rodmaia2099, bem lembrado. Basta considerar os projetos submetidos antes do projeto analisado. Estou fechando a issue.
