### ISSUE TITLE
Juntar features textuais e features categóricas na análise de similaridade de projetos

### ISSUE THREAD

**Issue by danielgs83** [lappis-unb/salic-ml#280]
Juntar features criadas na issue #257 com as features criadas na issue #245 em um vetor único de features que será usado na análise de similaridade entre projetos culturais. 

**Tarefas**

- [ ] Pegar features BOW e TF-IDF do resumo e título do projeto cultural, juntá-las ao vetor das features categóricas do projeto.
- [ ] Testar análise de similaridade com esse novo vetor de features combinado

**Critérios de aceitação**

- [ ] Notebook do experimento equivalente ao feito em https://github.com/lappis-unb/salic-ml/blob/projects_similarity/notebooks/doing/projects_similarity_feature_engineering.ipynb

**Comment by victorcmoura** [comment]
A discussão sobre features textuais extrapola o escopo definido no contexto atual do projeto
