### ISSUE TITLE
Post no Medium Salic-ML: Como implantar algoritmos de aprendizagem de máquina

### ISSUE THREAD

**Issue by danielgs83** [lappis-unb/salic-ml#286]
Post explicando como implantar algoritmos de aprendizagem de máquina - dos notebooks para API (Fazer estudo de caso salic ML)

**Tarefas**

- [ ] Escrever texto do post completo no Medium do projeto, incluindo perspectivas futuras e lições aprendidas
- [ ] Referenciar documentos e páginas Wiki do github do projeto

**Critérios de aceitação**

- [ ] Post publicado e revisado no Medium, com link.

**Comment by victorcmoura** [comment]
Documento em desenvolvimento: https://github.com/lappis-unb/salic-ml/wiki/Implementando-algoritmos-de-ml-em-prod

**Comment by victorcmoura** [comment]
Primeira versão do texto foi finalizada e está disponível no link do comentário acima.

**Comment by victorcmoura** [comment]
Artigo [disponível](https://medium.com/@lappisunbfga/o-uso-de-algoritmos-de-aprendizagem-de-m%C3%A1quina-em-produ%C3%A7%C3%A3o-estudo-de-caso-na-an%C3%A1lise-de-projetos-ed43ab86e5f6) mas com tradução pendente.
