### ISSUE TITLE
Documentação técnica do produto Salic-ML

### ISSUE THREAD

**Issue by danielgs83** [lappis-unb/salic-ml#289]
**Tarefas**

- [x] Documentação dos endpoints do gateway
- [ ] Documentar arquitetura do gateway

**Critérios de aceitação**

- [ ] Página na Wiki contendo as documentações

**Comment by eduardonunes2525** [comment]
Documentação: https://github.com/lappis-unb/salic-ml/wiki/Documenta%C3%A7%C3%A3o-dos-endpoints-da-API-do-Salic-ML

**Comment by victorcmoura** [comment]
Como a arquitetura está sendo retrabalhada, esta issue está sendo fechada. Em um outro momento, quando a nova refatoração estiver mais madura, uma nova issue será aberta.
