### ISSUE TITLE
Template/Roteiro de notebook

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#29]
Propor um template/roteiro para padronizar os notebooks e incentivar contribuições.

- [x] Olhar roteiro de outras organizações que usam aprendizagem de máquina

https://github.com/RochaCarla/serenata-de-amor/blob/master/research/develop/2017-05-11-anaschwendler-checking-federal-senate-reimbursements.ipynb

Ótima referencia:
https://www.kaggle.com/kabure/kickstarter-interactive-explanatory-exploration

https://github.com/RochaCarla/serenata-de-amor/blob/pyup-scheduled-update-2018-02-19/research/develop/2017-05-29-fgrehm-analysis-on-meals-based-on-presence-information.ipynb

- [x] Propor um roteiro/template para os notebooks

- [ ]  Refatorar os notebooks para adequar ao template

**Comment by Duerno** [comment]
Copiando a mensagem da issue #30:

A partir das lições aprendidas, dos estudos, fazer a documentação/tutorial (não sei qual a melhor forma de apresentar o conteúdo) do pipeline de projetos de aprendizagem de máquina (mais didático e objetivo possível):

- [ ] Sugestão: Usar o Appendix B do livro como referência (pág 505) -> livro hands-on machine learning with scikit-learn and tensorflow;

- [ ]  Fazer uma primeira versão genérica

- [ ] Fazer uma versão adaptada para o salic ml (especifico dos dados do minc etc)

**Comment by RochaCarla** [comment]
Dêem uma olhada em projetos interessantes de ML também (principalmente referente ao formalismo acadêmico). 
Achei essa boa referência:
https://github.com/facebookresearch/DensePose

**Comment by RochaCarla** [comment]
Vale a pena investir 👍 https://medium.com/netflix-techblog/notebook-innovation-591ee3221233
