### ISSUE TITLE
Refazer o componente de Comprovantes de pagamento

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#290]
Após uma reunião feita com os técnicos do MinC, foi sugerido que a métricas de comprovantes de pagamentos fosse estruturada de outra forma. Sendo esta: Separar *Comprovantes de pagamento* em três métricas separadas: *Comprovantes por Transferência*, *Comprovantes por Saque* e *Comprovantes por Cheque*. 

**Tarefas**

- [x] Definir como a métrica será exibida
- [x] Separar *Comprovantes de pagamento* em três métricas separadas: *Comprovantes por Transferência*, *Comprovantes por Saque* e *Comprovantes por Cheque*
- [x] Em *Comprovantes por Transferência*, acrescentar um link para as relações de pagamento do projeto
- [x] Em *Comprovantes por Saque*, acrescentar um link para as relações de pagamento do projeto
- [x] Em *Comprovantes por Cheque*, acrescentar um link para as relações de pagamento do projeto

**Critérios de aceitação**

- [ ] ~Estar disponível no Github pages~

**Comment by FranciscoSMM** [comment]
Ao criar a lista, vimos que seria necessário mudar o nome da métrica para que ficasse mais clara. Além disso incrementamos o símbolo de + e - para representar os valores extras e os valores faltando.

**Comment by FranciscoSMM** [comment]
Serão exibidas 3 métricas, uma vez que é necessário definir 3 pesos para cada tipo de avaliação. Além disso cada comprovante irá abrir em dropdown para mostrar os items relevantes.

**Comment by eduardonunes2525** [comment]
Confirmar a situação dos comprovantes e seus itens para saber se eles varios realmente tem comprovantes únicos ou não.

Além disso ainda falta implementar que itens que possuem o mesmo comprovante aumentam a complexidade da avaliação, uma vez que é preciso checar mais minunciosamente.
