### ISSUE TITLE
Refazer o componente de projetos por proponente

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#291]
Após a realização de uma reunião com os técnicos da SEFIC foi sugerido que no componente de projetos do mesmo proponente fosse  combinado as colunas Etapa e Situação em uma nova coluna Situação que mostre apenas o código da situação (E24, K00) e que indique o rótulo da etapa mais o rótulo da situação no tooltip da célula

**Tarefas**

- [ ] Combinar as colunas Etapa e Situação em uma nova coluna Situação
- [ ] Fazer um rótulo da etapa 

**Critérios de aceitação**

- [ ] Estar disponível no github pages

**Comment by victorcmoura** [comment]
Done
