### ISSUE TITLE
Evoluir o componente de Valor a ser Comprovado

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#292]
Ao invés de retornar somente o valor retornar também uma lista de itens orçamentários que não foram comprovados.

**Tarefas**

- [x] Fazer uma lista dos itens orçamentários que não foram comprovados

**Critérios de aceitação**

- [x] Estar disponível no github pages

**Comment by eduardonunes2525** [comment]
Notou se a possibilidade e a vantagem em criar uma nova métrica para representar a lista de itens orçamentários sem comprovante. Pois não há relação direta entre a métrica de valor a ser comprovado.

**Comment by FranciscoSMM** [comment]
Ao criar a lista, vimos que seria necessário mudar o nome da métrica para que ficasse mais clara. Além disso incrementamos o símbolo de + e - para representar os valores extras e os valores faltando.

**Comment by victorcmoura** [comment]
Dado que o componente foi evoluído e que falta implementar a feature no back-end, esta issue está sendo fechada.
