### ISSUE TITLE
Inverter a nota de complexidade do projeto

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#298]
Atuamente, a nota dada para o projeto apresenta se de forma invertida. Exemplo: Quando um projeto é categorizado como normal sua nota deve ser 1, pois trata se do nível de complexidade de análise. Hoje a nota apresenta como 10.

**Tarefas**

- [x] Inverter a lógica de definição da nota do nível de complexidade do projeto.

**Critérios de aceitação**

- [x] O nível de complexidade alto ser representada pela nota 10. E o menor nível de complexidade ser representada pela nota 1.

**Comment by victorcmoura** [comment]
Deve-se avaliar o comportamento atual da aplicação. Não há consenso definido sobre o que está acontecendo.

**Comment by fabiolamfleury** [comment]
A partir do PR #313 com a reestruturação do backend, a complexidade do projeto depende do peso das métricas(do indicador financeiro), que só são colocados caso o projeto seja outlier em tal métrica. Logo, a complexidade é menor quando um projeto é tido como 'normal'.

No  #316 foi feita a seguinte alterações: caso o projeto não possua no banco um indicador financeiro o retorno é que a complexidade daquele projeto é 0, como discutido em equipe

**Comment by fabiolamfleury** [comment]
Faltava ir para a master, feito na issue #324
