### ISSUE TITLE
Implementação de um protótipo para a arquitetura do salic-ml

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#3]
* [ ] Pesquisar viabilidade tecnológica
* [ ] Pesquisar e definir tecnologias de: banco de dados (incluindo cache), framework web, comunicação com sistemas externos, organização dos arquivos de pesquisa

**Comment by LucianoPC** [comment]
Vi um workflow de python com machine learning que trabalha como baixar e usar os dados csv sem mandar esses csv's para o github.

https://towardsdatascience.com/structure-and-automated-workflow-for-a-machine-learning-project-2fa30d661c1e

Eu segui o que a pagina mostra pra fazer e fiz um repositório com o tutorial deles:

https://github.com/LucianoPC/ml-study-download-data

**Comment by LucianoPC** [comment]
O código do machine learning vai ficar na arquitetura apresentada pelos links pesquisados, e será modularizado e instalado através do setup.py, podendo ser colocado no pip também.

Será utilizado um servidor, que pode ser o django ou o flask, que irá utilizar o módulo do machine learning e distribuir os dados através de uma API.

**Comment by LucianoPC** [comment]
![salic-ml](https://user-images.githubusercontent.com/3257415/43721483-485c22e2-9969-11e8-8f59-a6c0e3f16bf0.jpg)
