### ISSUE TITLE
Subir beta de homologação para validação pelos técnicos de análise financeira

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#305]
Deve existir um ambiente de homologação para que as novas features sejam validadas antes de irem para o ambiente de produção.

**Tarefas**
- [x] Definir infraestrutura para servir o ambiente de homologação
- [x] Subir ambiente de homologação

**Critérios de aceitação**
- [x] Aplicação beta disponível para os técnicos da análise financeira

**Comment by rodmaia2099** [comment]
Decidimos usar o GH Pages como ambiente de homologação: https://lappis-unb.github.io/salic-ml-frontend/#/
