### ISSUE TITLE
Consumir o novo backend no frontend

### ISSUE THREAD

**Issue by fabiolamfleury** [lappis-unb/salic-ml#307]
Com a #295 os endpoints e os resultados em json do backend foram alterados, logo devem ser feitas alterações no frontend para que a comunicação com o backend não tenha problemas.

**Tarefas**

- [ ] Alterar as chamadas dos endpoints para o novo formato implementado

- [ ] Alterar a leitura dos json

- [x] Atualizar a documentação: https://github.com/lappis-unb/salic-ml/wiki/Documenta%C3%A7%C3%A3o-dos-endpoints-da-API-do-Salic-ML

**Critérios de aceitação**

- [ ] As informações anteriormente disponibilizadas e visualizadas no frontend não devem sofrer alterações

**Comment by victorcmoura** [comment]
No review do dia 25/3, as pendências são:
- Atualizar a documentação
Dificuldades:
- Validação da integração
  - Infra para subir a API

**Comment by fabiolamfleury** [comment]
O backend deve ser alterado, as configurações da paginação vuetable 2, aproveitando que será criado um serializer, atualizar a ordenação para maior complexidade primeiro

**Comment by fabiolamfleury** [comment]
O backend foi alterado, criando-se um esquema de paginação customizado (api.config.pagination.CustomPagination)

**Comment by fabiolamfleury** [comment]
Outro problema que acabou por ser mapeado durante a realização dessa issue é que alguns projetos (Como exemplo o de PRONAC 090105) não tinham algumas métricas calculadas. A raíz desse problema foi encontrada nos scripts sql da aplicação, /data/scripts/planilha_orcamentaria.sql e /data/scripts/planilha_comprovacao.sql  que possuiam a seguinte limitação:
o SELECT limitava a seleção de projetos que foram iniciados depois de 2013, o pronac exemplo em questão começou em 2009, logo suas informações não estavam sendo coletadas. Alterou-se o sql para tirar este filtro, porém adicionou-se outra limitação: agora por ter dados de mais projetos, o calculo das métricas demora mais
