### ISSUE TITLE
Refatorar o docker da aplicação

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#308]
O docker da aplicação deve ser refeito para corrigir os problemas de conexão com o banco de dados.

**Tarefas**
- [x] Identificar os passos necessários para conectar a aplicação no banco de dados
- [x] Reproduzir os passos necessários dentro de um container docker
- [x] Refatorar o dockerfile atual para que seja possível executar a aplicação normalmente

**Critérios de aceitação**
- [x] Dockerfile atualizado com os requisitos necessários para se conectar ao banco de dados do Ministério
- [x] Docker image funcional e disponível em um registry público

**Comment by pablodiegoss** [comment]
A conexão com o banco remoto é feita utilizando uma VPN, as credenciais de acesso estão sendo compartilhadas entre a equipe e não são publicadas no github.
Dentre essas credenciais uma delas define o Host do banco de dados. Quando isso é usado localmente, o host é o próprio computador do usuário, então é a variável é definida como Localhost.
Na rede docker temos dois containers se comunicando, então utilizar a mesma configuração de localhost não funciona, pois o container Web tentaria acessar o banco em si mesmo (assim acusando o erro de banco indisponível), quando deveria acessar o serviço Salic_DB do outro container, então para corrigir a falha é necessário trocar as variáveis de acesso local para os nomes e portas na rede docker.

**Comment by pablodiegoss** [comment]
Após as modificações das variáveis locais foi possível rodar o projeto utilizando Docker, agora estou refatorando o Dockerfile e buscando uma forma de compartilhar as novas configurações privadas com a equipe.

**Comment by pablodiegoss** [comment]
Arquivos base com as variáveis de ambiente foram criados e devem ser preenchidos para que as imagens docker funcionem. Para evitar acidentes de commits com as informações preenchidas, pode ser executado localmente o comando:
```bash
git update-index --skip-worktree etc/env/db.env etc/env/vpn.env
```

**Comment by pablodiegoss** [comment]
O Docker file original foi quebrado em duas partes para maior agilidade no desenvolvimento local.

A decisão tomada foi de criar um `Dockerfile.base` que contém todas as dependencias da API SalicML, de modo que não seja necessário baixar isto a toda execução docker, somente será necessário modificar esta imagem em caso de atualizações ou novas dependências. E neste caso, foi criado um script `build-base.sh` que executa a construção da imagem e nomeação da mesma.

A aplicação então está concentrada no `Dockerfile` padrão, que utiliza a imagem citada anteriormente como base e copia os arquivos da aplicação. Esta é também a imagem utilizada no docker-compose.

As imagem foram construídas e publicadas no Dockerhub em uma [organização para a API salic](http://dockerhub.com/r/salicml). @victorcmoura e @rodrigocam foram adicionados como administradores.

**Comment by fabiolamfleury** [comment]
Faltava ir para a master, feito na issue #324
