### ISSUE TITLE
Melhorar performance da métrica "common_items_ratio"

### ISSUE THREAD

**Issue by rodrigocam** [lappis-unb/salic-ml#309]
Atualmente, esta métrica faz com que demore muito para realizar o treinamento. Verificar se é possível reduzir o tempo desta métrica.

**Tarefas**

- [ ] Usar o cache o máximo possível
- [ ] Balancear uso de memória com o de processamento

**Critérios de aceitação**

- [ ] Rodar todas as métricas em, no mínimo, 40 minutos em uma máquina com um processador i7 e 16gb ram

**Comment by fabiolamfleury** [comment]
Durante a execução do indicador financeiro não será utilizada essa métrica, porém, a métrica number_of_items também aparenta ser um gargalo

**Comment by fabiolamfleury** [comment]
fechada pois o problema mapeado foi maior do que apenas a métrica, mas sim o cálculo do indicador financeiro. A issue #323 continua o problema aqui levantado
