### ISSUE TITLE
Remover cálculo de métricas com peso zero

### ISSUE THREAD

**Issue by rodrigocam** [lappis-unb/salic-ml#310]
Algumas métricas estão com peso zero e portanto não influenciam no indicador final. É necessário criar algum mecanismo para não executar os cálculos destas métricas, assim melhorando a performance também.

**Tarefas**

- [x] Criar mecanismo para evitar cálculo das métricas com peso zero

**Critérios de aceitação**

- [x] O treinamento executar apenas as métricas com peso maior que zero

- [x] Adequar-se as observações descritas abaixo

**Comment by fabiolamfleury** [comment]
Observações:

- Existem métricas que possuem peso zero porém devem ser mostradas no front junto a complexidade financeira
- Outras métricas devem ser puxadas para os novos indicadores que serão utilizados em outros contextos que não na fase de análise financeira

**Comment by fabiolamfleury** [comment]
As métricas que foram retiradas do indicador financeiro:
- items_prices (precos_acima_media)
- approved_funds (valor_aprovado)
- raised_funds (valor_captado)
- common_items_ratio (itens_orcamentarios_fora_do_comum)

As métricas de valor aprovado e valor captado foram utilizadas na métrica de valor_a_ser_comprovado (to_verify_funds), o trabalho foi feito na branch  [i307_adapt_backend](https://github.com/lappis-unb/salic-ml/tree/i307_adapt_backend)

**Comment by fabiolamfleury** [comment]
Faltava ir para a master, feito na issue #324
