### ISSUE TITLE
Fazer a expansão do CNPJs em CPFs no grafo.

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#311]
Atualmente, os nós presentes nos grafos estudados podem representar tanto CPFs quanto CNPJs. O cenário ideal é um no qual apenas CPFs sejam nós. Para isso deve-se traduzir os nós que representam CNPJs em outros nós que representam os sócios (CPFs) desta empresa.

**Tarefas**

- [x] Listar CPFs de um dado CNPJ
- [x] Criar os nós referentes aos sócios de uma empresa
- [ ] ~Redirecionar as arestas dos CNPJs para os CPFs dos seus sócios~
- [ ] ~Implementar métodos nas listas de tuplas de incentivador e proponente~
- [ ] ~Implementar métodos nas listas de tuplas de proponente e fornecedor~
- [ ] ~Implementar métodos nas listas de tuplas de sociedades~

**Critérios de aceitação**

- [x] Existir métodos de se expandir os CNPJs de um grafo em CPFs no módulo Python
- [x] Exemplo de uso dos métodos

**Comment by victorcmoura** [comment]
No meio da sprint, chegou-se à conclusão de que não seria necessário lidar com grafos a nível de algoritmo e que, além disso, deveríamos nos reunir e pensar melhor sobre quais tipos de situação estávamos buscando. Houve, portanto, algumas mudanças:

- Por ser diretamente relacionada ao tipo de solução antes imaginada como ideal (expansão do grafo com a adição dos nós de sociedade), as tarefas e critérios de aceitação foram desconsiderados, uma vez que a abordagem para se resolver o problema foi trocada.
- Houve um brainstorm com a equipe para se discutir o tipo de situação a ser procurada no contexto das relações de sociedade. As formas resultantes foram disponibilizadas [num comentário na issue sobre estudo dos grafos](https://github.com/lappis-unb/salic-ml/issues/312#issuecomment-474458595)
- Os esforços foram direcionados para que houvesse um estudo sobre a primeira hipótese levantada. Este estudo foi concluído e apresentado aos outros membros da equipe. Os resultados estão disponíveis em um repositório privado para manter o sigilo das informações trabalhadas.

Dado que o novo escopo definido para a foi contemplado, esta issue está sendo fechada. A avaliação das demais hipóteses será planejada e demandará a criação de novas issues.
