### ISSUE TITLE
Primeiro contato com os grafos

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#312]
Entendimento dos grafos e pesquisa de bibliotecas compatíveis

**Tarefas**

- [x] Procurar bibliotecas compatíveis e com bom desempenho.
- [x] Entender o conceito dos grafos 
- [x] ~Entender quais são as anomalias e definir formas de mostrá-las~ Issue #320

**Critérios de aceitação**

- [ ] A biblioteca deve aceitar mais de 50000 nós
- [ ] A biblioteca deve trabalhar com JSON
- [ ] O conceito dos grafos está claro e definido
- [ ] A definição dos problemas a serem destacados deve estar definida
- [ ] Deve existir pelo menos uma forma de se mostrar esse gráfico na biblioteca escolhida.

**Comment by victorcmoura** [comment]
A limitação da lib utilizada para os estudos preliminares impede renderizar grafos com mais de 50 mil nós. Entretanto, em um dos grafos obtidos, existe mais de 70 mil nós. Por esta razão existe o requisito da possibilidade de se plotar grafos com mais de 50 mil nós.

**Comment by FranciscoSMM** [comment]
Conseguimos definir 4 "formas" iniciais para teste de parâmetro:
![image](https://user-images.githubusercontent.com/38992510/54615457-ea3efb00-4a3c-11e9-8f2b-d120afcd2ded.png)
![image](https://user-images.githubusercontent.com/38992510/54616045-dc3daa00-4a3d-11e9-8fe9-1c4e09134328.png)
![image](https://user-images.githubusercontent.com/38992510/54623867-1eb9b380-4a4b-11e9-9871-7556c02cfdbd.png)
![image](https://user-images.githubusercontent.com/38992510/54624019-5aed1400-4a4b-11e9-8f0a-9d680b832afb.png)

**Comment by FranciscoSMM** [comment]
Vou colocar aqui algumas bibliotecas que podem ser úteis talvez:

http://js.cytoscape.org/
http://visjs.org/showcase/index.html
http://visjs.org/network_examples.html

**Comment by rodmaia2099** [comment]
As formas 1 e 2 parecem corretas. A forma 3 pode ser um problema ou não, já que o proponente pode receber por fazer algumas atividades. Por exemplo, um proponente pode ser pago pelo projeto para fazer captação. Vamos identificar isso, mas com um peso menor de "gravidade" do problema.

Na forma 4, não precisa nem ser muito. Pode ser só uma vez. A princípio é errado incentivar o próprio projeto.

**Comment by joaaogui** [comment]
Em relação as bibiliotecas já testadas, foram testadas o Echarts e a D3.js. O echarts se mostrou inviavel para o uso com uma grande quantidade de nós, tendo um desemepenho pífio.

A D3 é um pouco mais complexa de configurar, o que causou com que não pudesse ainda ser testada em sua completude. Porém, por ela fazer uso de svg para os gráficos,como o echarts, existe a suspeita que o desempenho seja ruim.

O próximo passo é testar na [Chart.js](https://www.chartjs.org/), uma indicação do fábio, que disse ser fácil de configurar, e faz uso de canvas e nao svg, podendo ter um desempenho melhor.

**Comment by joaaogui** [comment]
Foi criada uma nova issue #320 para o estudo em relação as anomalias. 

A presente issue agora tem como foco o estudo das bibliotecas

**Comment by rodmaia2099** [comment]
@joaaogui @victorcmoura @eduardonunes2525 atualizem aqui pfv as ferramentas e as bibliotecas a evitar, segundo a conversa que tivemos com o Jackson.
