### ISSUE TITLE
Mudar o banco de dados local de sqlite para postgres

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#315]
Atualmente, o banco implementado é o sqlite. Deve-se trocar a tecnologia para evitar problemas com acessos simultâneos.

**Tarefas**

- [x] Trocar as configurações do Django para utilizar o adapter de postgres no lugar do adapter de sqllite

**Critérios de aceitação**

- [x] O banco executado deve ser postgres

**Comment by fabiolamfleury** [comment]
Realizado no PR #327 

Foi alterado no docker-compose o serviço de db para ser composto pelo postgresql, e também apontou-se no serviço do django que ele depende do postgresql. Ainda para evitar que o django inicialize antes do banco de dados e gere uma exceção, foi adicionado um script que trata essa exceção e tenta novamente conectar com o banco até receber sucesso.
