### ISSUE TITLE
Cuidar das articulações

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#317]
O ombro da Fabíola não está apresentando o comportamento esperado. Deve-se dar continuidade ao tratamento médico.

Edit1: O integrante Pablo também foi afetado. Deve haver uma busca para encontrar o fator comum entre as ocorrências de mal funcionamento das articulações.

Edit2: As costas do integrante Victor estão apresentando pequenos bugs. Providências serão tomadas.

**Tarefas**

- [x] Marcar consulta médica
- [ ] Comparecer à consulta médica
- [ ] Obedecer às recomendações médicas

**Critérios de aceitação**

- [ ] Redução do incômodo no ombro

**Comment by rodrigocam** [comment]
Indico tratamento com ventosas

**Comment by pablodiegoss** [comment]
@rodrigocam interessante, esses métodos não convencionais podem ser efetivos tbm, será que algo como acunpuntura ajuda?

**Comment by joaaogui** [comment]
@

> @rodrigocam interessante, esses métodos não convencionais podem ser efetivos tbm, será que algo como acunpuntura ajuda?

Artigo interessante sobre o assunto @pablodiegoss : https://www.cochrane.org/pt/CD005319/acupuntura-para-dor-no-ombro

**Comment by rodrigocam** [comment]
Parece que o problema de ombro esta se alastrando na nossa equipe, temos mais uma baixa

![photo4965717304054753305](https://user-images.githubusercontent.com/12930004/55168198-2b2bc380-5151-11e9-9a8f-e212ebe7a727.jpg)

**Comment by joaaogui** [comment]
Proponho uma quarentena para os dois com problema, afim de preservar a saude dos restantes. 

Talvez colocá-los para trabalhar na sala das mochilas ?

**Comment by victorcmoura** [comment]
A situação deve ser controlada antes que algo pior aconteça. Acredito que uma quarentena irá nos dar mais tempo para procurar o fator comum e eliminá-lo antes que ele derrube o restante da equipe. As autoridades responsáveis já estão sendo notificadas.

Att,
Victor Moura.

**Comment by victorcmoura** [comment]
Fui atingido, time. Mais um pra conta.

**Comment by rodmaia2099** [comment]
Acho que precisamos traçar um grafo para entender melhor a relação entre as pessoas afetadas e as não-afetadas. Depois podemos fazer um chatbot para marcar as consultas.

**Comment by BrunaNayara** [comment]
Já estou um pouco melhor. Mas quero deixar uma atualização sobre o status desse problema aqui no lappis
![image](https://user-images.githubusercontent.com/4125846/56895045-27e06c00-6a5e-11e9-950c-af1f8edc712b.png)

**Comment by rodrigocam** [comment]
Parece que o problema se alastrou para outras equipes, sugiro uma quarentena imediatamente!
