### ISSUE TITLE
Definir e implementar paralelização das métricas

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#322]
As métricas atualmente são calculadas pra um projeto por vez, com a implementação de técnicas de paralelização é possível utilizar mais núcleos do processador para calcular mais de um projeto por vez, assim diminuindo o tempo de processamento do treinamento.

**Tarefas**

- [x] Aplicar técnicas de paralelização no momento do treinamento das métricas

**Critérios de aceitação**

- [ ] Rodar o treinamento de todas as métricas financeiras para 28000 projetos em no máximo 40 minutos, em um computador com processador i5 e 8gb de memória ram.

**Comment by rodmaia2099** [comment]
@joaaogui  adiciona os detalhes por favor. Pode repassar para outra pessoa fazer isso tb.

**Comment by rodrigocam** [comment]
Editei a descrição adicionando mais informações relevantes sobre a issue

**Comment by rodrigocam** [comment]
Olhar o guia https://www.machinelearningplus.com/python/parallel-processing-python/

**Comment by rodrigocam** [comment]
Utilizando a biblioteca ```multprocessing``` do python, implementamos a paralelização do cálculo das métricas com base no número de processadores da máquina rodando o código.

Fazendo um teste com a métrica ```verified_approved```, em um computador com processador i5-4210U 1.7GHz constatamos que a mesma rodava em:
```
16min 41s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```
Após a técnica de paralelização, utilizando os 4 cores do computador:

```
8min 37s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```
O cálculo de todas as métricas (42405), com a técnica de paralelização agora roda em:

```
2h 23min 42s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```
