### ISSUE TITLE
Melhorar a performance da tarefa de cálculo de métricas na api

### ISSUE THREAD

**Issue by fabiolamfleury** [lappis-unb/salic-ml#323]
A task do invoke que calcula todas as métricas do Indicador Financeiro na api e salva no banco de dados, demora atualmente cerca de um dia, enquanto anteriormente demorava menos de uma hora.

**Tarefas**

- [x] Diminuir o número de requisições ao banco de dados do django

- [ ] ~~Estudar o tempo de execução dos métodos (Utilizar o cprofile do python para verificar)~~

- [x] Estudar a viabilidade de paralelização de tarefas

- [x] Verificar se é necessário aumentar o uso do cache

**Critérios de aceitação**

- [ ] ~~Balancear uso de memória com o de processamento~~
- [x] Problemas encontrados foram mapeados em issue(s)

**Comment by fabiolamfleury** [comment]
O @rodrigocam retomou essa issue, por ter finalizado as issues atribuidas de fato a sprint

**Comment by rodrigocam** [comment]
Atualmente o número de requisições ao banco foi bastante reduzido, fazendo todas as métricas rodarem em aproximadamente em 1.5 horas, porém o uso de memória está muito alto e existem meios de diminui-lo. Gostaria que a @fabiolamfleury testasse para ter certeza que todas as métricas estão sendo calculadas corretamente.
A respeito da paralelização, acredito ser bastante viável e benéfico para a performance deste cálculo.

**Comment by rodrigocam** [comment]
A respeito das tarefas de uso de memória e estudo  do tempo de execução dos métodos, foram criadas as respectivas issues: #329 #330

**Comment by victorcmoura** [comment]
Resta a @fabiolamfleury revisar a solução
