### ISSUE TITLE
Realizar integração das branches

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#324]
**Tarefas**

- [x] Mergar e resolver conflitos das branches (mlng, refactordocker, i309, i307)
- [x] O merge resultante deve ser a nova master do repositório 

**Critérios de Aceitação**

- [x] Não desconsiderar estrutura de pastas da branch i307 no merge final
- [x] Não desconsiderar refatoração da branch i309
- [x] O backend deve funcionar como esperado

**Comment by fabiolamfleury** [comment]
Foram integradas as branches e testadas as funcionalidades. Primeiramente todas as branchs (refactordocker, i309, i307) foram mergeadas na mlng. Não houveram conflitos por conta de pastas e arquivos renomeados, então parte do trabalho teve que ser feito manualmente. Depois que conferidas as funcionalidades do backend a mlng foi adicionada na master
