### ISSUE TITLE
Atualização do banco de homologação

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#325]

**Comment by rodmaia2099** [comment]
Usar histórico da issue #226 como referência nas conversas com o Ministério

**Comment by victorcmoura** [comment]
Por questões estratégicas, esta issue não foi realizada na Sprint 21.

**Comment by victorcmoura** [comment]
@rodmaia2099 irá tratar do assunto na próxima reunião, marcada para o dia 10/4

**Comment by rodmaia2099** [comment]
Uma nova versão do banco estava disponível a partir de 12/4

**Comment by joaaogui** [comment]
Afim de se fechar a issue, comparar os dados do banco atual com dados de projetos mais novos do versalic.

**Comment by rodmaia2099** [comment]
Comparado e confirmado que foi atualizado.
