### ISSUE TITLE
Prototipar exemplos da primeira hipótese de relação de sociedade

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#326]
Issue #312

**Tarefas**

- [x] Desenhar exemplos de visualização das primeira hipótese identificada na issue [312](https://github.com/lappis-unb/salic-ml/issues/312#issuecomment-474458595)
- [ ] Prototipar os exemplos no echarts
- [ ] Identificar exemplos com: Poucos sócios, quantidade média de sócios e um com uma cacetada de sócios

**Critérios de Aceitação**

- [ ] As visualizações devem estar disponiveis online para qualquer um acessar
- [ ] Os protótipos devem estar contidos no diretório "prototypes"
- [ ] Os gráficos devem ser facilmente interpretados por alguém externo à issue/equipe

**Comment by rodmaia2099** [comment]
Exploramos algumas possibilidades de grafos e confirmamos  a hipótese que já havia sido levantanda por alguns membros da equipe: não precisamos de grafos em certos casos.

Quando fazemos a análise dentro do mesmo projeto, a tendência é ter grafos muito pequenos e as relações entre CPFs que são normais, servem apenas para gerar ruído. Por isso, optamos por explorar outros formatos de representação. Esses formatos talvez possam ser reaproveitados quando fizermos grafos mais complexos, que atravessem vários projetos.

**Comment by rodmaia2099** [comment]
![photo4958552005819869211](https://user-images.githubusercontent.com/13748586/55028488-9311cb00-4fe6-11e9-8b25-98ace485f9d2.jpg)

Exemplo de como um grafo com representação "genérica" de nós e diferenciação da representação das relações não funciona muito bem.

**Comment by rodmaia2099** [comment]
![photo4958552005819869210](https://user-images.githubusercontent.com/13748586/55028570-d10eef00-4fe6-11e9-80d2-897d86393190.jpg)

Exemplo de como um grafo representando um problema dentro do mesmo projeto pode parecer simples demais.

**Comment by FranciscoSMM** [comment]
rascunhos para alternativas de visualização de sociedade e de potenciais problemas:

1. Mostrar as sociedades a partir de CPFs agrupados. O problema aqui seriam muitas sociedades sobrepostas, o que pode causar confusão.
![image](https://user-images.githubusercontent.com/38992510/55029111-07993980-4fe8-11e9-8be0-54c0abb829c5.png)


2. Cada CPF possui símbolos demonstranto suas funções. Nesse caso, os símbolos já indicariam problemas, mas seria difícil quando houvesse um volume mais alto.
![image](https://user-images.githubusercontent.com/38992510/55029348-a32aaa00-4fe8-11e9-8dc9-abf585f80618.png)


3. Ressaltar as relações problemáticas entre CPFs. NEsse caso precisaria de algo a mais para especificar quais são tais relações. Também existe a possibilidade de muitas relações.
![image](https://user-images.githubusercontent.com/38992510/55029567-24823c80-4fe9-11e9-920a-545b249fdb20.png)

4. Cada link mostra uma relação que houve entre cada CPF, Se estiver ressaltado, indica relação problemática e ao dar hover mostra quais as funções de cada um durante tal relação.
![image](https://user-images.githubusercontent.com/38992510/55029711-85117980-4fe9-11e9-87ac-676af291d7ac.png)

5. Mostra apenas as relações até segundo grau de um CPF. No caso, poderia ser escolhido qual CPF está analisando.
![image](https://user-images.githubusercontent.com/38992510/55029866-e9ccd400-4fe9-11e9-9d00-bf29971c8971.png)

6. Essa seria a primeira ideia, onde o projeto ficava em evidencia e seu quadro societário ao redor. Como da para ver, isso rapidamente faz com que as coisas saiam do controle quando existem muitos quadros e muitas funcões.
![image](https://user-images.githubusercontent.com/38992510/55030330-eede5300-4fea-11e9-8eee-58a3ef8ffb82.png)

7. Nesse caso, apenas as relações problemáticas receberiam link, mesmo que todos os cpfs apareçam. 
![image](https://user-images.githubusercontent.com/38992510/55030556-68764100-4feb-11e9-8dc5-a8c69815d69e.png)

8. Essa ultima ideia foi a que ficou mais completinha no sentido de, apenas os membros problemáticos de cada sociedade são destacados ao fazerem interceção com outras sociedades. NEsse caso cada ciclo poderia representar uma empresa, mas caso isso acontecesse não precisaria links internos
![image](https://user-images.githubusercontent.com/38992510/55031159-ba6b9680-4fec-11e9-9a0b-614b20f3afd3.png)

**Comment by rodmaia2099** [comment]
Depois da conversa que tivemos com o Jackson Maia, especialista em ciência da informação da CGEE, vamos mudar a abordagem dos grafos.
Por isso, vamos dar alguns passos atrás em relação à forma de apresentar os grafos. Esta issue vai depender de uma nova análise. Até lá, permanece em suspenso.

**Comment by joaaogui** [comment]
O ultimo exemplo está disponivel no echarts em http://graph-nodes.surge.sh/
