### ISSUE TITLE
Melhorar o uso de memória no cálculo de métricas

### ISSUE THREAD

**Issue by rodrigocam** [lappis-unb/salic-ml#329]
Atualmente o treino de métricas está consumindo bastante memória. Com algumas otimizações é possível reduzir bastante este consumo.

**Tarefas**

- [x] Eliminar problema de swap no servidor
- [ ] Usar chunks de dados
- [x] Limpar listas da memória

**Critérios de aceitação**

- [x] Reduzir o uso de memória pela metade
- [ ] Não aumentar o tempo de processamento em detrimento do uso de memória

**Comment by victorcmoura** [comment]
Percebeu-se que o problema com a memória ocorre de maneira crítica quando há o retreino das métricas:

![image](https://user-images.githubusercontent.com/26290053/58807699-f7589880-85ee-11e9-9686-10d8c904105f.png)

**Comment by rodmaia2099** [comment]
"Você quer performance, não fique de bobeira! Chame o João e o Rodrigo Oliveira!"

**Comment by rodrigocam** [comment]
O problema que estava acontecendo era que ao criar vários processos para calcular a métrica de vários projetos, estes processos precisavam de uma cópida dos dados utilizados, assim uma máquina com 20 CPU's, precisaria de 20 * (tamanho dos dados necessários para o cálculo desta métrica), por isso ocorria o estouro de memória.
Agora o código de paralelização está sendo feito por métrica, o que significa que se em todo o salic tiverem 10 métricas, 10 processos paralelos serão utilizados, reduzindo bastante o consumo de memória, mas aumentando um pouco o tempo de cálculo de métricas.
