### ISSUE TITLE
Bug: Projetos do mesmo proponente.

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#331]
Na atual métrica, não aparece as informações da tabela. Pois o que é enviado do back é somente o pronac dos projetos do mesmo proponente.

**Tarefas**

- [x] Investigar e corrigir o motivo de determinados atributos não estarem contidos no json.
- [x] Evitar problemas de recursividade.

**Critérios de aceitação**

- [ ] Disponibilizar a API com os dados necessários para mostrar a tabela no front.
- [ ] Dados que devem ser exibidos: complexidade dos outros projetos, nome, valor comprovado valor captado, situação do projeto, e período de execução.
- [ ] Corrigir os valores captado e comprovado

**Comment by fabiolamfleury** [comment]
Outro problema encontrado: na lista de projetos do proponente, o próprio projeto aparece

**Comment by fabiolamfleury** [comment]
A correção dos valores comprovados e captados foi feita da seguinte forma:

A task de inv update-models, depois de popular o banco com os projetos, faz mais duas requisições no banco do MinC, uma para valores captados e outra para valores comprovados

**Comment by rodmaia2099** [comment]
Os dados ainda não aparecem no front. Qual o problema?

**Comment by joaaogui** [comment]
Investigar o que aconteceu no decorrer da issue, já que os dados realmente nao aparecem na front.

**Comment by eduardonunes2525** [comment]
Aparentemente, o método que cria e calcula a métrica de projetos do mesmo proponente não está sendo chamando. Desta forma, a métrica já foi implementada só que o método não está sendo chamado.

**Comment by victorcmoura** [comment]
Foi revisado e o problema persiste

**Comment by rodmaia2099** [comment]
Continua em #409
