### ISSUE TITLE
Criar links na métrica de comprovantes com extrapolação acima de 50%

### ISSUE THREAD

**Issue by fabiolamfleury** [lappis-unb/salic-ml#333]
Atualmente, a métrica de comprovantes com extrapolação acima de 50%, não possui links para o salic.  Portanto, a métrica deve possuir, assim como na métrica de novos fornecedores, links para a planilha de comprovantes.

Links para planilha :
* salic.gov.br/projeto/#/{PRONAC}/relacao-de-pagamento

**Tarefas**

- [x] Colocar este link no front direto.

**Critérios**

- [x] O front deve estar exibindo o link .

**Comment by joaaogui** [comment]
Falta fazer o deploy no servidor e arrumar o link no front.

**Comment by victorcmoura** [comment]
No ambiente de homologação atual, o componente não aparenta ter href. Imagina-se que, mesmo com [o href presente](https://github.com/lappis-unb/salic-ml-frontend/blob/829de4bfd7c41f1c28d0c11cbb2778cbf4fbb816/src/components/show_metrics/content_metric/SimpleListContent.vue#L5), este não está sendo mostrado por falta da informação passada pelo backend. O mal comportamento deve ser resolvido quando houver um deploy da API em uma versão mais recente.

**Comment by joaaogui** [comment]
Já é possivel verificar que foi feito ?

**Comment by rodmaia2099** [comment]
Os links serão retirados conforme documentado em #390
