### ISSUE TITLE
Corrigir exibição de links dentro da métrica de Novos Fornecedores

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/salic-ml#335]
Deve se observar a existencia da planilha readequada. Caso ela exista, a mesma deve ser usada. Caso não exista, usa-se a planilha homologada.

Links para planilha orçamentária:
* salic.gov.br/projeto/#/{PRONAC}/planilha-homologada
* salic.gov.br/projeto/#/{PRONAC}/planilha-readequada

**Tarefas**

- [x] Rever onde os dados de itens orçamentários estão sendo buscados.
- [ ] Aplicar url correta dependendo do tipo de planilha.
- [ ] Definir uma raiz estática para a URL
- [x] Corrigir a posição (identação) do link na página
- [x] Ordenar nomes de fornecedores alfabeticamente
- [x] Adicionar link dos novos fornecedores de forma geral 
- [x] Remover o link de cada novo fornecedor 
- [x] Modificar o atual formato do json para:
```json
{
    "nome": "FAG PRODUCOES E EVENTOS LTDA - ME",
    "cnpj": 10540539000197,
    "link": "/prestacao-contas/analisar/comprovante/idPronac/188791/uf/41/produto/122/idmunicipio/410690/idPlanilhaItem/3864/etapa/2",
    "itens": [
            {
                "nome": "Locação de Microfones ",
                "tem_comprovante": true
                 }
            ]
},

                                
```

**Critérios de aceitação**
- [ ] Links corrigidos estão disponíveis no GitHub Pages e funcionando

**Comment by rodmaia2099** [comment]
Durante a revisão do front (#339) me ocorreu que poderíamos ter um link único no *sticky header* tanto para a planilhade itens orçamentários quanto para a lista de comprovantes de pagamento. O que vocês acham? Isso eliminaria a necessidade de links específicos em cada item.

**Comment by fabiolamfleury** [comment]
Procurando no banco de dados, não foi encontrado onde existe a diferenciação entre a utilização no projeto da planilha homologada ou readequada, foi decidido que continuará essa busca

**Comment by fabiolamfleury** [comment]
Lugares que podem possuir informações:
* SAC.dbo.tbDetalhaPlanoDistribuicaoReadequacao

**Comment by rodmaia2099** [comment]
Os links serão retirados conforme documentado em #390
