### ISSUE TITLE
Implementar a métrica de comprovantes por código de operação

### ISSUE THREAD

**Issue by fabiolamfleury** [lappis-unb/salic-ml#336]
A métrica foi estudada na issue #262 e deve possuir implementação e disponibilização no backend

**Tarefas**

- [x] Criar no salicml a métrica, subdividida em três 

- [x] Colocar os pesos da métrica no backend, separadamente (Comprovantes por código de operação (TED, saque, cheque) 5/5/1

**Critérios de aceitação**

- [x] A métrica deve seguir os padrões estabelecidos pelo componente do frontend

**Comment by fabiolamfleury** [comment]
As métricas foram implementadas, agora estão sendo feitas adaptações para seguir o seguinte modelo de saida:

  "comprovantes_de_cheque": {
      "valor": 0,
      "valor_valido": False,
      "is_outlier": False,
      "minimo_esperado": 0,
      "maximo_esperado": 0,
      "data": {
        "comprovantes": "id_comprovante" : "itens": [{}],
      }
  },
  "comprovantes_de_saque": {
       "valor": 0,
       "valor_valido": False,
       "is_outlier": False,
       "minimo_esperado": 0,
       "maximo_esperado": 0,
       "data": {
         "comprovantes": "id_comprovante" : "itens": [{}],
       }
   },
  "comprovantes_de_transferencia": {
       "valor": 0,
       "valor_valido": False,
       "is_outlier": False,
       "minimo_esperado": 0,
       "maximo_esperado": 0,
       "data": {
         "comprovantes": "id_comprovante" : "itens": [{}],
       }
   },

**Comment by joaaogui** [comment]
Foi observado que algumas dessas métricas estão duplicadas, o bug será investigado em #388
