### ISSUE TITLE
Criar parametro(filter) para busca por Pronac

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#338]
O frontend possui uma barra para filtro que não funciona no momento. Ela deve funcionar filtrando os projetos pelo PRONAC.

**Tarefas**

- [x] Adicionar tratamento para parametro filtro na url de lista de projetos
- [x] Retornar lista de projetos filtrada de acordo com parametro passado 
- [x] Mudar as variáveis de start execution e end execution de char para data

**Critérios de aceitação**

- [ ] ~A barra de filtro filtra os projetos de acordo com o PRONAC digitado~

**Comment by fabiolamfleury** [comment]
Tentou-se utilizar o DjangoFilterBackend do pacote django_filters, e não houve o resultado esperado. Estou procurando outros jeitos de fazer isso sem ter que reescreve o código que o django boogie gera pra gente da api

**Comment by joaaogui** [comment]
Como próximo passo, deve-se conversar com o fábio afim de se conseguir uma solução pelo django boogie.

**Comment by fabiolamfleury** [comment]
Usando o django boogie, é possível receber de um endpoint sua queryset e a request, com o query_hook:

@rest_api.query_hook('analysis.Project')
def query(request, qs):
   return qs

O queryset pode ser manipulado para que filtragem ocorra


Sugestão do professor Fábio:
usar lazy property para nota de complexidade do projeto

**Comment by fabiolamfleury** [comment]
Quanto a filtragem por PRONAC, ela já está feita, pois os endpoints refereciam diretamente por pronac, basta procurar host:8000/v1/projects/{PRONAC}/details/

**Comment by fabiolamfleury** [comment]
Em relação as outras filtragens, elas seguem o padrão do django, alguns exemplos são:

host:8000/projects?nome__icontains=agricultura  -> retorna os projetos que possuem o termo agricultura, independente das letras estarem maiúsculas ou minúsculas
host:8000/projects?nome__contains=agricultura ->  retorna os projetos que possuem o termo agricultura é case sensitive!

**Comment by fabiolamfleury** [comment]
@victorcmoura @eduardonunes2525 vocês podem validar a possibilidade de filtrar por pronac no front end?

**Comment by victorcmoura** [comment]
@fabiolamfleury é inviável implementar o filtro completamente no frontend. São muitos dados a serem processados no browser e, em algum momento do ano passado, esta solução provou-se inadequada dados os requisitos de desempenho.

**Comment by joaaogui** [comment]
Issue fechada em favor da #368
