### ISSUE TITLE
Revisar a interface do relatório de complexidade e da lista de projetos

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/salic-ml#339]
Fizemos muitas mudanças na lista de projetos e no relatório. Precisamos revisar a interface para identificar problemas de experiência.

**Tarefas**

- [x] Revisar interface 
- [x] Abrir issues para problemas complexos ou corrigir problemas simples

**Critérios de aceitação**

- [x] Todos os problemas de experiência foram documentados ou resolvidos

**Comment by FranciscoSMM** [comment]
- Não da para organizar por nome, ou pronac, etc.
- O texto todo está em português, mas a quantidade de itens mostrada na página está em inglês. (no final, canto esquerdo da página)
- Existem acentos e letras que não possuem suporte da FONTE escolhida.
- Precisa padronizar o nome dosresponsáveis.
- Na página do projeto é falta ainda centralizar a posição das setas algumas das métricas possuem "*" indicando que tem alguma explicação extra, mas isso não aparece em nenhum lugar da página.
- Vermelho e verde não são boas cores para pessoas daltônicas, isso pode ser resolvido mudando o verde para algum tom de azul.
- Quando navegando para a parte inferior da página, o overlay que aparece tem uma cor que não corresponde a cor inicial da nota.
- Na nálise da segunda métrica (extrapolação de 50%) não precisa ter um sinal, seja ele de + ou de -, já que se aparece lá, já demosntra que passou de 50% permitido.

**Comment by rodmaia2099** [comment]
- Na lista de projetos, fixar largura das colunas de PRONAC e Complexidade que variam de uma página de resultados à outra
- Na lista de projetos, avaliar a possibilidade de permitir saltar para uma página específica
- Na lista de projetos, avaliar a possibilidade de permitir mudar a quantidade de registros por página
- Ao voltar do relatório para a lista de projetos, a paginação não é guardada, ou seja, sempre volta para a página 1
- Adicionar espaço antes de "(R$)" na tabela de detalhes de Valor a ser comprovado
- Deixar a tabela de detalhes de Valor a ser comprovado com largura "automática" para aproximar o valor do nome do item
- Tentar eliminar quebra de linha no título de "Comprovantes com extrapolação acima de 50% do aprovado"
- BUG????: Comprovantes com extrapolação acima de 50% do aprovado lista itens com menos de 50%
- Mostrar itens de Comprovantes com extrapolação acima de 50% do aprovado em ordem alfabética 
- Reduzir espaço entre as linhas de itens de Comprovantes com extrapolação acima de 50%
- Arredondar porcentagem nos itens de Comprovantes com extrapolação acima de 50% do aprovado em ordem alfabética
- Em "Comprovantes com extrapolação acima de 50% ", em "Projetos do mesmo proponente" e em "Novos fornecedores", "não disponível" significa que não existem outros projetos ou que houve algum erro? Se for a primeira opção, substituir o texto "não disponível" por "nenhum
- Em "Novos fornecedores", ordenar fornecedores alfabeticamente 
- Em "Novos fornecedores", aumentar o espaço entre as linhas com nomes de fornecedores
- Em "Novos fornecedores", corrigir a indentação dos itens de cada fornecedor

**Comment by rodmaia2099** [comment]
O @FranciscoSMM eu eu listamos os problemas aqui temporariamente. Vou triar tudo e ver o que podemos corrigir já e o que precisamos abrir issues.

**Comment by rodmaia2099** [comment]
Fiz vários ajustes pequenos -> https://github.com/lappis-unb/salic-ml-frontend/pull/14

**Comment by FranciscoSMM** [comment]
Ao falar com a @fabiolamfleury e um pouco com o @eduardonunes2525 vimos que as issues criadas a partir dessa análise, #346 - #353, são possíveis de serem feitas ou já estavam com algum nível de completude. Aparentemente elas não serão muito complexas, mas nem todas possuem uma possível solução ainda.
