### ISSUE TITLE
Integrar componente de comprovantes de pagamento com a api

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#340]
**Tarefas**

- [x] Integrar o trabalho da api feito na issue #336 com o componente feito em #290

**Critérios de aceitação**

- [x] O frontend deve disponibilizar o componente de comprovantes de pagamentos com dados reais providos pela api
- [x] Disponível no github pages
- [x] Conseguir identificar projetos que tenham mais de um comprovante por código de operação (no github pages)
- [x] Tirar o "*" depois de confirmar a integração nas métricas que estão mockadas

**Comment by fabiolamfleury** [comment]
Foi acordado entre front e back o modelo da métrica e foram implementadas, falta testar de fato se a integração funciona
