### ISSUE TITLE
Criar endpoint com métricas para a etapa de admissibilidade

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#341]
Reaproveitar a métrica que lista itens orçamentários fora do comum para compor a versão inicial do pacote de métricas direcionadas à admissibilidade.

**Tarefas**

- [ ] ~~Criar endpoint específico para novo pacote~~
- [x] Listar itens inesperados presentes (Em ordem alfabética) 
- [x] Listar itens esperados ausentes (Em ordem alfabética)
- [ ] ~~Redefinir organização arquitetural (semântica) das métricas que podem compor mais de um indicador (Conversar com Joênio e/ou Fábio)~~

**Critérios de aceitação**

- [ ] O endpoint deve estar disponível online na API.

**Comment by rodrigocam** [comment]
A necessidade de consultar um sênior (Fábio ou Joênio) foi reavaliada, já que a estrutura das classes modelos não foram alteradas. O indicador de admissibilidade pode ser obitido da mesma maneira que o indicador financeiro, sendo então não necessária a criação de um novo endpoint.

**Comment by rodmaia2099** [comment]
Retornando para in-progress enquanto o PR estiver aberto
