### ISSUE TITLE
Ordenar projetos por todos os campos da tabela

### ISSUE THREAD

**Issue by FranciscoSMM** [lappis-unb/salic-ml#346]
Atualmente os projetos se organizam apenas por ordem decrescente de Nota. Caso o usuário queira mudar essa ordem, ordenar por resonsável ou algum outro parâmetro, não é possível.

**Tarefas**

- [x] Criar backend para essa organização
- [x] Poder ordenar por Pronac (crescente e decrescente)
- [x] Poder ordenar  por Nota de complexidade (crescente)
- [x] Poder organizar por nome (crescente e decrescente)
- [x] Poder organizar por Responsável (crescente e decrescente)

**Critérios de aceitação**

- [ ] ~É possível clicar em cada aba e organizar por aquele parâmetro (no GH Pages)~
- [x] É possível recuperar as ordenações pela API

**Comment by FranciscoSMM** [comment]
precisa ainda do backend

**Comment by fabiolamfleury** [comment]
@FranciscoSMM @rodmaia2099 além da ordenação, serão feitos filtros desses parametros?

**Comment by rodmaia2099** [comment]
Só ordenação

**Comment by fabiolamfleury** [comment]
Foram implementadas as ordenações no backend, na branch i338_filter_projects

 - Poder ordenar por Pronac 
    * crescente: host:8000/v1/projects?order_by=pronac
    * decrescente: host:8000/v1/projects?order_by=-pronac

-  Poder ordenar por Nota de complexidade (crescente)
    * crescente: host:8000/v1/projects?order_by=complexidade
    * decrescente: host:8000/v1/projects/

-   Poder organizar por nome (crescente e decrescente)
    * crescente: host:8000/v1/projects?order_by=nome
    * decrescente: host:8000/v1/projects?order_by=-nome
-   Poder organizar por Responsável (crescente e decrescente)
    * crescente: host:8000/v1/projects?order_by=responsável
    * decrescente: host:8000/v1/projects?order_by=-responsável
