### ISSUE TITLE
[BUG] Comprovantes de extrapolação mostram valores menores do que 50%

### ISSUE THREAD

**Issue by FranciscoSMM** [lappis-unb/salic-ml#350]
Alguns dos valores que aparecem quando se checam os itens da métrica de comprovantes com extrapolação de porcentagem aparecem com números menores do que 50%. Isso acaba por ser suspeito uma vez que apenas itens com maiores porcentagens deveriam aparecer

**Tarefas**

- [x] Revisar o que significam os números mostrados nessa métrica.
- [x] certificar que apenas os valores maiores do que 50% estão sendo mostrados.
- [x] Trocar o hífen por algum outro indicador para não confundir com sinal de "-" (menos).

**Critérios de aceitação**

- [ ] Apenas valores maiores do que 50% estão sendo mostrados.

**Comment by FranciscoSMM** [comment]
talvez hajam alguns outros bugs que devem ser documentados. Fabiola comentou sobre o de pronacs e projetos do mesmo proponente.

**Comment by fabiolamfleury** [comment]
Consegui identificar o problema: os itens mostrados estavam corretos, o que não estava é a porcentagem (a relação de porcentagem estava invertida, mostrando qual era a porcentagem do valor aprovado em relação ao comprovado).
