### ISSUE TITLE
Verificar o uso de "Não disponível" nas métricas

### ISSUE THREAD

**Issue by FranciscoSMM** [lappis-unb/salic-ml#352]
Em "Comprovantes com extrapolação acima de 50% ", em "Projetos do mesmo proponente" e em "Novos fornecedores", "não disponível" significa que não existem outros projetos ou que houve algum erro? Se for a primeira opção, substituir o texto "não disponível" por "nenhum" 

**Tarefas**

- [x] verificar se a frase aparece quando não há comprovantes
- [x] Verificar se a frase aparece quando há erro
- [x] Analisar se seria melhor substituir por "0" ou "nenhum"

**Critérios de aceitação**

- [x] A frase representa melhor o que está acontecendo em cada métrica.

**Comment by rodmaia2099** [comment]
Após revisar com a equipe, identificamos que "não disponível" realmente é diferente do valor zero e tudo está correto
