### ISSUE TITLE
Preparar datasets para apresentação do workshop de Machine Learning

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#36]
- [ ] Dataset relacionado precificação de itens de projetos
- [ ] Dataset relacionado a categorização de área ou segmento de projetos

**Comment by marlonbymendes** [comment]
Dataset preparados, entretando não foi possível fazer o upload dos `.csv` para este repositório, por conta de: #37.

Porém o script `SQL` que gerou o dataset está disponível aqui: https://github.com/lappis-unb/salic-ml/blob/master/data/scripts/planilha_aprovacao.md.
