### ISSUE TITLE
Reconfigurar cronjob que recalcula periodicamente as métricas

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#369]
O cronjob implementado não funciona por conta das modificações feitas no backend.

**Tarefas**

- [x] Trocar comandos da aplicação antiga para comandos da aplicação mais recente
- [x] Investigar a possibilidade de se usar o timer do systemd (30 min) (https://wiki.archlinux.org/index.php/Systemd/Timers)

**Critérios de aceitação**

- [ ] O banco deve apresentar, semanalmente, as métricas atualizadas com as modificações mais recentes implementadas.

**Comment by rodmaia2099** [comment]
Retornando para in-progress enquanto o PR estiver aberto

**Comment by victorcmoura** [comment]
Como combinado no planning, modificou-se apenas os comandos necessários para se executar o cálculo semanal dos dados do sistema. O PR contém as alterações em questão: https://github.com/lappis-unb/salic-ml/pull/375/files

**Comment by joaaogui** [comment]
O cronjob foi feito de forma correta, porém os logs do serviço não apresentaram infos sobre as mudanças. Deve-se investigar o por que.
