### ISSUE TITLE
Disponibilizar arquivos com informações privadas em máquina local

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#371]
Existem planilhas que hoje são publicas, porém contém dados privados. A solução é disponibilizá-los localmente no lappis, com acesso por ssh.

**Tarefas**

- [x] Configurar acesso ssh na máquina
- [x] Colocar arquivos na máquina 
- [x] Definir um pipeline de download dos arquivos

**Critérios de aceitação**

- [x] Os arquivos devem estar disponiveis por acesso ssh

**Comment by joaaogui** [comment]
Os arquivos estão no diretório salic-ml/data/raw/.

O acesso SSH é feito pelo comando: 

`ssh lappis@164.41.98.12 -p 13508`

**Comment by joaaogui** [comment]
Um exemplo de linhade comando para download dos arquivos:

`sudo scp -P 13508 -r lappis@164.41.98.12:/home/lappis/salic-ml/data/raw/ /home/joao/test`

**Comment by rodmaia2099** [comment]
@joaaogui os outros membros da equipe conseguiram baixar os arquivos?

**Comment by joaaogui** [comment]
@rodmaia2099 As coisas mudaram um pouco, segue o próximo comentário.

**Comment by joaaogui** [comment]
O @arthurbdiniz implementou uma vpn para o lappis, o que siginifica que não será possivel acessar o servidor utilizando o ip externo do mesmo, para isso, é necessário ter a vpn configurada.

Para se configurar a VPN é necessário primeiramente ter um usuário no OPNsense, caso não tenha deve se contatar ou o @arthurbdiniz ou o @joenio.

Depois de se ter um usuário, deve-se acessar o OPNsense em 192.168.100.1, logar com seu usuário, ir na barra lateral em VPN > OPENVPN > Client Export. Nessa página deve se navegar até Client Install Packages, no nome do seu usuário, clicar no dropdown de export e a seguir em Archive.

Seguindo esses passos, um arquivo .zip com suas configurações será baixado na sua máquina, com isso, deve se utilizar o openvpn(sudo apt install openvpn), para se iniciar o tunelamento com a VPN, seguindo os seguintes comando: 

`unzip <arquivo_baixado.zip>`
`cd <pasta_criada>`
`sudo openvpn --config <nome_de_usuario_XYZ>.ovpn`

Com isso, a sua máquina estará simulando uma conexão local dentro do lappis, o que possibilita a execução do seguinte comando (com o ip local do servidor), para se copiar os arquivos:

`sudo scp -r lappis@10.0.0.30:/home/lappis/salic-ml/data/raw/ /home/joao/test`

**Comment by rodmaia2099** [comment]
Entendi. Vou pedir pro @joenio criar esses usuários pra gente

**Comment by rodmaia2099** [comment]
Entendi. Vou pedir pro @joenio criar esses usuários pra gente.
