### ISSUE TITLE
Fazer ordenação dos campos da tabela de projetos no front

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/salic-ml#373]
Atualmente os projetos se organizam apenas por ordem decrescente de Nota. Caso o usuário queira mudar essa ordem, ordenar por responsável ou algum outro parâmetro, não é possível.

## Tarefas

- [x] Poder ordenar por Pronac (crescente e decrescente)
- [x] Poder ordenar por Nota de complexidade (crescente e decrescente)
- [x] Poder organizar por nome (crescente e decrescente)
- [x] Poder organizar por Responsável (crescente e decrescente)

## Critérios de aceitação

- [x] É possível clicar em cada aba e organizar por aquele parâmetro (no GH Pages)

**Comment by rodmaia2099** [comment]
@eduardonunes2525 acabei de testar o front ficou muito bom! A complexidade parece que não está ordenando de forma crescente. Também precisamos indicar que a tabela está ordenada por complexidade decrescente por padrão, ou seja, mostrar a seta assim que carregar.

**Comment by eduardonunes2525** [comment]
@rodmaia2099 a respeito da ordenação da complexidade realmente não está funcionando, era um bug do backend. Porém, já submeti um PR com a correção do mesmo: #377. Em relação a exibição da ordenação padrão já realizei essas modificações e já se encontra no github pages.

**Comment by rodmaia2099** [comment]
Excelente @eduardonunes2525!

**Comment by joaaogui** [comment]
Investigar se existe melhor solução para a intuição do usuário sobre a ordenação de todos os campos, nao só complexidade.
