### ISSUE TITLE
Aumentar memória da máquina do servidor

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/salic-ml#374]
A maquina que se encontra o salic-ml tem somente 4GB de ram, é necessário adicionar mais memória (min 8GB)

### Tarefas 

- [x] Ver possibilidade de adicionar mais memória na máquina que se encontra o sistema.

### Critérios de Aceitação  

- [x] A máquina tem no mínimo 8GB de ram
- [x] As métricas rodam sem utilização do SWAP

**Comment by rodrigocam** [comment]
A máquina que roda nossa aplicação agora possui 16GB de memória RAM

**Comment by rodmaia2099** [comment]
Parou de fazer swap?

**Comment by rodrigocam** [comment]
Ainda não possuímos esta informação, pois não conseguimos rodar as métricas por completo devido a um erro no código, acredito que o @joaaogui esteja trabalhando na correção e até o fim desta sprint teremos uma resposta!

**Comment by rodmaia2099** [comment]
@joaaogui linka a issue nova como sendo blocante dessa aqui. Eu procurei aqui, mas não encontrei.

**Comment by joaaogui** [comment]
Bloquei @rodmaia2099

**Comment by joaaogui** [comment]
Aconteceram várias mudanças na infra do lappis desde que essa issue foi criada, que fazem com que ela mude um pouco o foco. Pra sumarizar:

1. O backend deixou de rodar em uma máquina positivo, e hoje está rodando em uma lâmina do servidor.
2. Com isso, a memória disponivel para o serviço é facilmente setada pela interface dos mesmos.
3. Em um teste com o @victorcmoura, foi possivel observar que rodar as métricas utilizou em média 10 GB de RAM, então proponho setarmos a memória Para 12 GB.

**Comment by joaaogui** [comment]
Issue continuada em #386
