### ISSUE TITLE
Colocar em homologação um ambiente para servir os dados do ML

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#38]
- [x] Criar uma aplicação django básica e dockerizar
- [ ] Colocar a aplicação django em homologação no LAPPIS
- [x] Colocar a aplicação django em homologação no MinC
- [ ] Colocar algum indicador e servir na aplicação django

**Comment by LucianoPC** [comment]
**Colocar a aplicação django em homologação no MinC**

Fui informado que já tem uma VM no MinC para a API, estou aguardando receber o acesso à VM.

**Comment by victorcmoura** [comment]
A issue continua em https://github.com/lappis-unb/salic-ml-web/issues/15
