### ISSUE TITLE
Função que invalida temporariamente os pickles não está revalidando após o fim do uso dos pickles de teste

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#382]
Há uma função que invalida os pickles originais para não serem utilizados no modo teste. Mas, após o uso dos dataframes de teste, os pickles originais não estão sendo renomeados para o estado anterior. O resultado é este:

![image](https://user-images.githubusercontent.com/26290053/57951364-2fa66a00-78c0-11e9-910a-8682f5d8fc9b.png)

**Tarefas**

- [x] Investigar a razão do erro
- [x] Documentar na issue o resultado obtido pela tarefa acima
- [x] Implementar solução se for viável ou abrir issue para a correção

**Critérios de aceitação**

- [x] Comentários nesta issue contendo a explicação do erro
- [x] Problema corrigido ou issue aberta para correção

**Comment by rodrigocam** [comment]
O erro que estava dando é que o código que voltava os nomes dos pickles para o normal estava logo abaixo da chamada das métricas e se as métricas falhassem, por algum motivo, este código não era executado. Agora utilizei um `try` para executar este código sempre. Corrigido junto no PR #367
