### ISSUE TITLE
Bug na métrica de novos fornecedores

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#383]
Atualmente, os dados fornecidos pela API estão duplicados. O mesmo novo fornecedor é repetido para cada item orçamentário em que participa. Isso acaba afetando o escore geral de complexidade do projeto.

**Tarefas**

- [x] Investigar como foi implementada a métrica
- [x] Agrupar itens orçamentários de um mesmo novo fornecedor.

**Critérios de aceitação**

- [x] Dados não estarem mais duplicados expostos na API.
- [x] Métrica de novos fornecedores não ter duplicações no frontend.

**Comment by rodrigocam** [comment]
O que estava ocorrendo neste bug é que cada item novo encontrado, não era feito uma cerificação se seu fornecedor já constava na lista e portanto adicionava na lista o fornecedor existente. Agora fiz essa verificação e os itens do mesmo forncedor são listados corretamente.
