### ISSUE TITLE
Investigar métricas duplicadas no retorno da API

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#388]
Observou-se que a métrica "comprovantes_de_saque" possui uma versão duplicada, chamada "comprovantes_saque", no JSON da api. Deve-se procurar mais duplicatas e verificar qual deve ser removida (qual delas está de fato retornando as informações desejadas).

**Tarefas**

- [x] Fazer levantamento das métricas duplicadas
- [x] Identificar quais as métricas que devem ser removidas
- [x] Remover duplicatas

**Critérios de aceitação**

- [x] O retorno da api não pode conter duplicatas nas métricas de um projeto

**Comment by rodrigocam** [comment]
O que estava ocorrendo é que no dicionário de métricas com valores default, os nomes das métricas de comprovantes estavam diferentes dos nomes das métricas de fato, o que ocasionava em duplicatas nesses retornos, padronizei os nomes e o erro parece ter sido consertado.

**Comment by rodrigocam** [comment]
Descobri outros problemas relacionados e farei outro PR  de correções assim que possível
