### ISSUE TITLE
Métrica comprovante_acima_50 não está sendo mostrada corretamente na API

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml#389]
Olhando no db, um projeto que possuía a métrica calculada como outlier era o com pronac 163829. Entretanto, na resposta da API, esta métrica consta com os valores default (como se não houvesse dados o suficiente para calcular a métrica).

**Tarefas**

- [ ] ~Identificar problema do backend~ (Não se sabe a razão exata do problema)
- [ ] ~Corrigir problema do backend~ (Não houve correção, já que não identificou-se o problema)

**Critérios de aceitação**

- [x] Encontrar projeto que tenha a métrica calculada como outlier
- [x] O projeto encontrado deve ter a sua resposta no backend assim como encontrada no banco
- [x] O front deve mostrar a informação enviada pela API

**Comment by victorcmoura** [comment]
Rodei novamente o treinamento das métricas e, agora, o resultado mostrado na API condiz com o que existe no banco de dados:

![image](https://user-images.githubusercontent.com/26290053/58668312-f1bd3300-830e-11e9-8514-a25670f4e003.png)

Entretanto, mesmo com a API retornando o valor correto, não é possível observar o mesmo comportamento no frontend:

![image](https://user-images.githubusercontent.com/26290053/58668378-11545b80-830f-11e9-87f0-c2c35e8451db.png)

Os links para a verificação do comportamento demonstrado pelas prints seguem abaixo:

API: https://salicml.lappis.rocks/v1/projects/163829/details/
Frontend: https://lappis-unb.github.io/salic-ml-frontend/#/projetos/indicador_financeiro/163829

O projeto que foi usado como validação é o mesmo apontado na descrição da issue: Pronac 163829

**Comment by victorcmoura** [comment]
O @eduardonunes2525 fez algumas refatorações no backend com o @rodrigocam. O objetivo era diferente, entretanto, o problema desapareceu após os commits novos. A recomendação é considerar a issue como fechada, mas permanecer observando o comportamento dos futuros treinamentos.

Além disso, deve-se investigar a razão do frontend não estar exibindo corretamente a informação enviada pela API.

**Comment by victorcmoura** [comment]
Verifiquei que no frontend ele estava usando o antigo nome da métrica: "comprovantes_acima_de_50". Atualmente, no json, o nome é: "comprovantes_acima_50". Realizei a modificação e o resultado foi positivo:

![image](https://user-images.githubusercontent.com/26290053/58669065-5da09b00-8311-11e9-94b8-96f62e69d003.png)

**Comment by joaaogui** [comment]
Issue será fechada, vide comentários da descrição. 

Em relação a duplicação da métrica, foi criada a issue #406
