### ISSUE TITLE
Bug valor a ser comprovado

### ISSUE THREAD

**Issue by eduardonunes2525** [lappis-unb/salic-ml#393]
Atualmente, a métrica está sendo considerada incompleta por não conter a lista e itens que faltam ser comprovados.

**Tarefas**

- [x] Verificar a viabilidade de implementação da métrica

**Critérios de aceitação**

- [x] Issue aberta em caso de correção da métrica ou justificativa para não implementar mudanças

**Comment by rodmaia2099** [comment]
Revisamos a métrica e realmente não tínhamos nenhum dado disponível. Considerando a meta de finalizar o relatório de complexidade de análise financeira, vamos optar por indicar apenas o valor sem detalhar os itens orçamentários.
