### ISSUE TITLE
Spike - Inferir Complexidade do Projeto

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#41]
Fazer uma avaliação exploratória para verificar se há um indicador de complexidade de projeto..

Rating quanto a

- [ ] Complexidade financeira - quantidade de projetos caros (porcentagem)

- [ ] Complexidade temporal - projetos de longo prazo de execução

- [ ] Complexidade de serviço - projetos com muitos itens de prestação financeira

- [ ] Complexidade de fornecedores - fornecedores novos vs fornecedores conhecidos vs fornecedores conhecidos + problemas

Critérios de avaliação:

1. Extrair essas medidas

1. Avaliar o histograma

1. Para cada um, encontrar uma "formula" de ratings

**Comment by Duerno** [comment]
Oi, Carla. A análise dos indicadores de complexidade do projeto foram divididos em épicos e tarefas e já estão sendo explorados. Essa issue está muito macro e por isso será fechada, mas será possível acompanhar a evolução do trabalho da equipe através das issues e milestones do projeto.
