### ISSUE TITLE
Levantamento de Features

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#42]
Documentar quais são os principais dados das propostas da lei Rouanet, quais principais features. 

- [ ] Levantar as features do projetos

- [ ] Documentação

**Comment by RochaCarla** [comment]
Artigo de seleção de feature:

http://www.jmlr.org/papers/volume3/guyon03a/guyon03a.pdf

**Comment by Duerno** [comment]
Oi Carla, estamos separando e analisando os dados relacionados às finanças de projetos culturais na issue #44, replicaremos o estudo para outros indicadores em breve. Fecharei essa issue, para acompanhar nosso trabalho sobre levantamento e seleção de features, veja a issue #44.
