### ISSUE TITLE
Spike - Estudo de ferramentas de ML big data

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#43]
Ver como podemos implementar ML em produção?

- [ ] Olhar Spark

- [ ] Olhar Zeppelin

- [ ] Quais outras estratégias usar?

**Comment by Duerno** [comment]
Oi Carla, estamos estudando sobre a melhor forma de colocar em produção um sistema que forneça os dados encontrados pelo grupo de ML. A issue #38 acompanha a evolução de tal sistema. Por conta de estar duplicada, esta issue será fechada.
