### ISSUE TITLE
Aplicar algoritmos de clusterização ao dataset de finanças e inspecionar os outliers

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#46]
- [ ] Pesquisar principais algorítmos de clusterização
- [ ] Aplicar algoritmos mais adequados ao dataset
- [ ] Inspecionar outliers e discutir o significado dos resultados no mundo real

**Comment by Duerno** [comment]
Esta issue foi dividida em outras, durante o [Brainstorming de features para estimar Complexidade Financeira](https://github.com/lappis-unb/salic-ml/wiki/Brainstorming-de-features-para-estimar-Complexidade-Financeira)
