### ISSUE TITLE
Criar dados mockados de indicadores

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#51]
- [ ] Mockar a função de treinamento dos algoritmos, por exemplo, definir a mediana
- [ ] Receber um ID de Projeto, pegar os resultados do algoritmo mockado relativos a esse projeto e popular o banco de dados

**Comment by marlonbymendes** [comment]
Ja está sendo usado os dados reais, logo essa issue não é mais necessário
