### ISSUE TITLE
Converter os notebooks os algoritmos de calculo de indicador

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#54]
- [ ] Definir as entradas e saídas
- [ ] Implementar as queries para obter os dados
- [ ] Implementar o algoritmo de treinamento
- [ ] Implementar o cálculo do indicador

**Comment by marlonbymendes** [comment]
Caixa preta:

Entrada: pronac
Saída: lista de valores reais

**Exemplo:**

Entrada = 172085
Saída: [outlier=True,  numero_de_itens=183, média_do_segmento=123, desvio_padrão=50]
