### ISSUE TITLE
migrar servidor de conexão a vpn do minc para infra própria do lappis

### ISSUE THREAD

**Issue by joenio** [lappis-unb/salic-ml#64]
migrar serviço de conexão a vpn/minc (issue #59) para infra do próprio lappis, alugar vpn na digitalocean na conta do lappis ou subir um container no rancher com IP público e re-fazer o setup.

**Comment by joenio** [comment]
configurar nesse mesmo servidor o gitlab runner, e registrar como runner no pipeline, dessa forma reduzimos 1 nível na complexidade, uma vez que iremos executar o pipeline na máquina já conectada a VPN do minc.

referencia sobre gitlab runner:
* https://docs.gitlab.com/runner/

**Comment by victorcmoura** [comment]
Issue transferida para https://github.com/lappis-unb/salic-ml-web/issues/26
