### ISSUE TITLE
Como a planilha orçamentária foi modificada ao longo do tempo

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#65]
Como os itens (edição, adição ou remoção de itens) e os preços mudam ao longo do tempo

**Entrada:** Pronac
**Saída:**

- Quantidade de planilhas (da primeira aprovada até a última aprovada) modificadas
- Soma das alterações por planilha
- Se o projeto é outlier ou não em relação ao seu segmento
- O quão outlier o projeto é, caso ele seja um outlier

**Comment by marlonbymendes** [comment]
Os dados necessários para fazer esta feature estão indisponíveis no banco de homologação, uma coluna necessária está 100% com valores `null`, (tabela: SAC.dbo.tbPlanilhaAprovacao, coluna: idPlanilhaAprovacaoPai). A decisão tomada foi de não fazer esta feature agora, indo para a próxima feature priorizada na lista: https://github.com/lappis-unb/salic-ml/issues/60.

É importante que as demais equipes ajam de acordo: @eduardonunes2525 @victorcmoura

**Comment by marlonbymendes** [comment]
Após atualização do banco de dados de homologação para refletir o banco de dados de produção, a coluna `idPlanilhaAprovacaoPai` agora possui algumas linhas não nulas. A seguinte query foi executada para confirmar esta informação:

```
SELECT idPlanilhaAprovacao, idPlanilhaAprovacaoPai
FROM SAC.dbo.tbPlanilhaAprovacao 
WHERE idPlanilhaAprovacaoPai IS NOT NULL;
```

**Comment by Mattioli** [comment]
Achamos que, no contexto do tópico 2, seja interessante mostrar uma lista dos itens que foram modificados, para que o técnico possa analisá-los melhor.

As perguntas são:
- acham valioso mostrar os itens ao usuário?
- se sim: como é o acesso deles a essas modificações dos itens via salic? eles conseguem ver todas as versões das modificações ou apenas a última? no primeiro caso: mostrar só a última ou todas?
- enxergam outra coisa a mais a ser dada como output?
