### ISSUE TITLE
Atualizar o banco de homologação periodicamente

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#83]
Alterei o nome dessa issue de "Acesso ao banco de dados de produção do Salic" para "Atualizar o banco de homologação periodicamente"

Foi criada outra issue "Acesso ao banco de dados de produção do Salic" #113 
Foi criada uma issue para atualizar o banco de homologação que está no LAPPIS com o banco de homologação no MinC #114

**Comment by LucianoPC** [comment]
Conversei com o Marcus e ele me encaminhou para o Thiago, porém o Thiago não pode me dar essa permissão, no momento estou conversando com o Heron.

Contatos no Telegram:
Marcus: @MarcusVinicus
Thiago: @ThiagoLinux
Heron: @heronbonfim

**Comment by LucianoPC** [comment]
Conversei com o Heron e ele me respondeu a seguinte mensagem: "Luciano, esse tipo de permissão só posso conceder se o Marcus Menezes, coordenador de sistemas do MinC, solicitar formalmente".

Vou entrar em contato com o Marcus.

**Comment by LucianoPC** [comment]
Enviei a mensagem a baixo hoje (14/08/2018 às 14:02) para o Paulo Henrique, estou esperando a resposta.

Contatos no Telegram:
Paulo: @paulohmoreira

<br/>

**Mensagem:**

Oi Paulo, boa tarde,

Eu sou o Luciano, trabalho no LAPPIS, o laboratório da UnB, no projeto com o MinC, estou trabalhando no salic-api e tambem na utilização de machine learning para auxiliar os técnicos na análise financeira no Salic

Nós temos acesso ao banco de dados de homologação, porém agora não está sendo o suficiente para a gente

Queria ver contigo a possibilidade de termos acesso de leitura ao banco de produção do Salic, tanto para ver se a evolução que fizemos na api está com os dados coerentes em relação a api em produção, quanto para podermos fazer o sistema de machine learning com os dados corretos.

**Comment by paulohmoreira** [comment]
Boa noite Luciano, acredito que meu perfil foi erroneamente linkado nesse problema, não tenho nenhum vínculo com o Salic.

**Comment by LucianoPC** [comment]
Conversei com o Heron, eles vão replicar o banco de produção para o de homologação, ou seja, o banco de homologação estará identico ao banco de produção, ele também disse que pode atualizar o banco de produção em intervalos pequenos de tempo para manter o banco de homologação atualizado. Temos que avaliar se isso é o suficiente para homologar com os técnicos do MinC.

**Comment by LucianoPC** [comment]
O Heron disse que vai atualizar o banco de homologação toda sexta-feira a partir das 14h, é um processo que leva mais de 3h.

**Comment by victorcmoura** [comment]
Esta issue pode ser fechada?

**Comment by victorcmoura** [comment]
Issue fechada pois a periodicidade das atualizações foi definida
