### ISSUE TITLE
Adicionar links no front para o Salic

### ISSUE THREAD

**Issue by marlonbymendes** [lappis-unb/salic-ml#85]
Links:
- Itens
- Fornecedores
- Projeto

- [ ] Mapear como montar o link, identificar os ID's necessários
- [ ] Abrir uma issue para ser colocado os ID's no módulo ML, se necessário
- [ ] Adicionar links na view
- [ ] Testar os links em pelo menos 5 projetos diferentes

**Comment by victorcmoura** [comment]
Issue transferida para https://github.com/lappis-unb/salic-ml-web/issues/1
