### ISSUE TITLE
Adequar repositório aos padrões da comunidade de software livre

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/salic-ml#9]
Adequar o repositório para atender os padrões da comunidade de software livre (ref).
https://github.com/lappis-unb/salic-ml/community

- [x] Inserir licença GPL3V

- [x] Contribuição (política de branch, as especificadades de submissão no caso do ML )

- [x] Readme (aplicar template)
- [x] templates de issues, e pull requests

**Comment by Duerno** [comment]
Oi, o pull request #57 trabalha nessas atualizações e está referenciado pela issue #14. Acompanhe as melhorias por lá, ok? :)
