### ISSUE TITLE
Salvar o calculo dos indicadores no banco de dados

### ISSUE THREAD

**Issue by LucianoPC** [lappis-unb/salic-ml#97]

**Comment by rodmaia2099** [comment]
Além de salvar os cálculos no banco precisamos decidir a periodicidade em que isso vai acontecer porque isso impacta diretamente o uso do cliente ML. A gerente da prestação de contas precisa ser capaz de olhar para a lista de projetos a qualquer momento e usar a métrica de complexidade para distribuir projetos entre os técnicos.

**Comment by victorcmoura** [comment]
Issue transferida para https://github.com/lappis-unb/salic-ml-web/issues/23
